/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.21
 * Generated at: 2019-09-28 11:21:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.patent;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class patent_005fuse_005flist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1562034500000L));
    _jspx_dependants.put("jar:file:/C:/Users/창민/Documents/GitHub/GoodDeV/ChanMin/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/GoodDeV/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("<title>Neutral ::</title>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("\tcontent=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"/cloud/resources/css/open-iconic-bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/cloud/resources/css/animate.css\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/cloud/resources/css/owl.carousel.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"/cloud/resources/css/owl.theme.default.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/cloud/resources/css/magnific-popup.css\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/cloud/resources/css/aos.css\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/cloud/resources/css/ionicons.min.css\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/cloud/resources/css/flaticon.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/cloud/resources/css/icomoon.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/cloud/resources/css/style.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/cloud/resources/css/search.css\">\r\n");
      out.write("\r\n");
      out.write("<script src=\"/cloud/resources/js/jquery-3.4.1.min.js\"></script>\r\n");
      out.write("<script src=\"/cloud/resources/js/jquery-ui.min.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("$(function(){\r\n");
      out.write("\t\r\n");
      out.write("\t$(\".pri\").on('click', function(){\r\n");
      out.write("\t\tvar tempContractDate=$(this).attr(\"data-contractDate\");\r\n");
      out.write("\t\t$('#contractDate').val(tempContractDate);\r\n");
      out.write("\t\tvar patentNum = $(this).attr(\"data-value\");\r\n");
      out.write("\t\t$('#patentNum').val(patentNum);\r\n");
      out.write("\t\tvar pti_seq = $(this).val();\r\n");
      out.write("\t\t$('#Pti_seq').val(pti_seq);\r\n");
      out.write("\t\tvar itemNum = $(this).attr(\"data-id\");\r\n");
      out.write("\t\t$('#itNum').val(itemNum);\r\n");
      out.write("\t\tvar documentNum = $(this).attr(\"data-name\");\r\n");
      out.write("\t\t$('#DocumentNum').val(documentNum);\r\n");
      out.write("\t\tvar memId = $(this).attr(\"data-member\");\r\n");
      out.write("\t\t$('#memberId').val(memId);\r\n");
      out.write("\t});\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t $('.pri').on('click',function(){\r\n");
      out.write("\t\tvar itemNum = $(this).attr(\"data-id\");\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl : 'down',\r\n");
      out.write("\t\t\ttype : 'get',\r\n");
      out.write("\t\t\tdata : {\r\n");
      out.write("\t\t\t\t\"itemNum\" : itemNum\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tsuccess : function(res){\r\n");
      out.write("\t\t\t\t$('#down').html(res);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t})\r\n");
      out.write("\t\r\n");
      out.write("\t})  \r\n");
      out.write("\t $('.pri').on('click',function(){\r\n");
      out.write("\t\tvar itemNum = $(this).attr(\"data-id\");\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl : 'down1',\r\n");
      out.write("\t\t\ttype : 'get',\r\n");
      out.write("\t\t\tdata : {\r\n");
      out.write("\t\t\t\t\"itemNum\" : itemNum\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tsuccess : function(res){\r\n");
      out.write("\t\t\t\t$('#down1').html(res);\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t})\r\n");
      out.write("\t\r\n");
      out.write("\t})  \r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t$('#down').on('click',function(){\r\n");
      out.write("\t\tvar itemNum =$('#itNum').val();\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl : 'download',\r\n");
      out.write("\t\t\ttype : 'get',\r\n");
      out.write("\t\t\tdata : {\r\n");
      out.write("\t\t\t\t\"itemNum\" : itemNum\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tsuccess : function(resp) {alert('성공')},\r\n");
      out.write("\t\t\terror : function(a, b, c) {alert('실패'+ a+\", \" + b + \",\" + c)}\r\n");
      out.write("\t\t})\r\n");
      out.write("\t\r\n");
      out.write("\t})\r\n");
      out.write("\t\r\n");
      out.write("\t$('#down1').on('click',function(){\r\n");
      out.write("\t\tvar itemNum =$('#itNum').val();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl : 'download1',\r\n");
      out.write("\t\t\ttype : 'get',\r\n");
      out.write("\t\t\tdata : {\r\n");
      out.write("\t\t\t\t\"itemNum\" : itemNum\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tsuccess : function(resp) {alert('성공')},\r\n");
      out.write("\t\t\terror : function(a, b, c) {alert('실패'+ a+\", \" + b + \",\" + c)}\r\n");
      out.write("\t\t})\r\n");
      out.write("\t\r\n");
      out.write("\t})\r\n");
      out.write("\t\r\n");
      out.write("\t $('#permitBtn').on('click',function(){\r\n");
      out.write("\t\tvar formData = new FormData($('#permitionForm')[0]);\r\n");
      out.write("\t\tvar upload = $('#upload').val();\r\n");
      out.write("\t\tif(upload.length==0||upload==\"\"){\r\n");
      out.write("\t\t\talert('파일을 반드시 첨부하세요!');\r\n");
      out.write("\t\t\treturn false;\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tvar itemNum =$('#item-option option:selected').attr(\"data-value\");\r\n");
      out.write("\t\tvar del = $('.pri').parent().parent();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl : 'permitionForm',\r\n");
      out.write("\t\t\ttype : 'post',\r\n");
      out.write("\t\t\tenctype : 'multipart/form-data',\r\n");
      out.write(" \t\t\tprocessData : false,\r\n");
      out.write(" \t\t\tcontentType : false,\r\n");
      out.write(" \t\t\tdata : formData,\r\n");
      out.write("\t\t\tsuccess : function(res){\r\n");
      out.write("\t\t\t\tif(res=='success'){\r\n");
      out.write("\t\t\t\t\talert(\"성공\");\r\n");
      out.write("\t\t\t\t\t$('#exampleModal').modal('hide');\r\n");
      out.write("\t\t\t\t\tdel.remove();\r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\talert(\"실패\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t})\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t})\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body data-spy=\"scroll\" data-target=\".site-navbar-target\"\r\n");
      out.write("\tdata-offset=\"300\">\r\n");
      out.write("\r\n");
      out.write("\t<nav\r\n");
      out.write("\t\tclass=\"navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light site-navbar-target\"\r\n");
      out.write("\t\tid=\"ftco-navbar\">\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<a class=\"navbar-brand\" href=\"/cloud/home\">MainLogo</a>\r\n");
      out.write("\t\t<button class=\"navbar-toggler js-fh5co-nav-toggle fh5co-nav-toggle\"\r\n");
      out.write("\t\t\ttype=\"button\" data-toggle=\"collapse\" data-target=\"#ftco-nav\"\r\n");
      out.write("\t\t\taria-controls=\"ftco-nav\" aria-expanded=\"false\"\r\n");
      out.write("\t\t\taria-label=\"Toggle navigation\">\r\n");
      out.write("\t\t\t<span class=\"oi oi-menu\"></span> Menu\r\n");
      out.write("\t\t</button>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"collapse navbar-collapse\" id=\"ftco-nav\">\r\n");
      out.write("\t\t\t<ul class=\"navbar-nav nav ml-auto\">\r\n");
      out.write("\t\t\t\t<li class=\"nav-item\"><a href=\"/cloud/home\" class=\"nav-link\"><span>Home</span></a></li>\r\n");
      out.write("\t\t\t\t<!--  <li class=\"nav-item\"><a href=\"search_menu\" class=\"nav-link\"><span>검색</span></a></li>-->\r\n");
      out.write("\t\t\t\t<li class=\"nav-item\"><a href=\"#FAQ-section\" class=\"nav-link\"><span>특허 FAQ</span></a></li>\r\n");
      out.write("\t\t\t\t<li class=\"nav-item\"><a href=\"survey_list\" class=\"nav-link\"><span>블라인드 테스트</span></a></li>\r\n");
      out.write("\t\t\t\t<li class=\"nav-item\"><a href=\"funding_list\" class=\"nav-link\"><span>크라우드 펀딩</span></a></li>\r\n");
      out.write("\t\t\t  ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t  ");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("  \r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</nav>\r\n");
      out.write("\r\n");
      out.write("\t<section class=\"hero-wrap hero-wrap-2\"\r\n");
      out.write("\t\tstyle=\"background-image: url('/cloud/resources/images/about_10-1.jpg');\"\r\n");
      out.write("\t\tdata-stellar-background-ratio=\"0.5\">\r\n");
      out.write("\t<div class=\"overlay\"></div>\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<div\r\n");
      out.write("\t\t\tclass=\"row no-gutters slider-text align-items-end justify-content-center\">\r\n");
      out.write("\t\t\t<div class=\"col-md-9 ftco-animate pb-5 text-center\">\r\n");
      out.write("\t\t\t\t<h1 class=\"mb-3 bread\">Check Patent</h1>\r\n");
      out.write("\t\t\t\t<p class=\"breadcrumbs\">\r\n");
      out.write("\t\t\t\t\t<span class=\"mr-2\"><a href=\"index\">Home <i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"ion-ios-arrow-forward\"></i></a></span> <span class=\"mr-2\"><a\r\n");
      out.write("\t\t\t\t\t\thref=\"blog.html\">특허 <i class=\"ion-ios-arrow-forward\"></i></a></span> <span>특허\r\n");
      out.write("\t\t\t\t\t\t사용 신청 확인<i class=\"ion-ios-arrow-forward\"></i>\r\n");
      out.write("\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<section class=\"ftco-section\" id=\"blog-section\">\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<div class=\"row justify-content-center mb-5 pb-5\">\r\n");
      out.write("\t\t\t<div class=\"col-md-10 heading-section text-center ftco-animate\">\r\n");
      out.write("\t\t\t\t<span class=\"subheading\"></span>\r\n");
      out.write("\t\t\t\t<h2 class=\"mb-4\">특허 사용 신청 확인</h2>\r\n");
      out.write("\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t특허에 대한 사용 신청자 목록입니다.<br> 사용 허가를 원하실 경우 사용 신청서와 허가서를 첨부해주세요.<br>\r\n");
      out.write("\t\t\t\t\t각 회원님이 사용 신청서 및 사용 허가서를 소지한 시점부터 효력이 발휘됩니다.\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<hr class=\"hr_navy\">\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"search-result\" id=\"search-result\">\r\n");
      out.write("\t\t\t<table class=\"table\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t <thead class=\"navy\">\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th scope=\"col\">No.</th>\r\n");
      out.write("\t\t\t\t\t\t<th scope=\"col\">분류</th>\r\n");
      out.write("\t\t\t\t\t\t<th scope=\"col\">특허명</th>\r\n");
      out.write("\t\t\t\t\t\t<!--<th scope=\"col\"></th>-->\r\n");
      out.write("\t\t\t\t\t\t<th scope=\"col\">사용 신청자</th>\r\n");
      out.write("\t\t\t\t\t\t<th scope=\"col\">신청날짜</th>\r\n");
      out.write("\t\t\t\t\t\t<th colspan=\"2\" scope=\"col\"></th>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t</tbody> \r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t<!--페이징 & 검색-->\r\n");
      out.write("\t\t\t<div class=\"page-center\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<nav>\r\n");
      out.write("\t\t\t\t<ul class=\"pagination justify-content-center\">\r\n");
      out.write("\t\t\t\t\t<li class=\"page-item\"><a class=\"page-link\"\r\n");
      out.write("\t\t\t\t\t\taria-label=\"Previous\"> <span aria-hidden=\"true\">&laquo;</span>\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"sr-only\">Previous</span>\r\n");
      out.write("\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"page-item active\"><a class=\"page-link\">1</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"page-item\"><a class=\"page-link\">2</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"page-item\"><a class=\"page-link\">3</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"page-item\"><a class=\"page-link\">4</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"page-item\"><a class=\"page-link\">5</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"page-item\"><a class=\"page-link\" aria-label=\"Next\">\r\n");
      out.write("\t\t\t\t\t\t\t<span aria-hidden=\"true\">&raquo;</span> <span class=\"sr-only\">Next</span>\r\n");
      out.write("\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</nav>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<hr class=\"hr_navy\">\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</section>\r\n");
      out.write("\r\n");
      out.write("\t<!-- loader -->\r\n");
      out.write("\t<div id=\"ftco-loader\" class=\"show fullscreen\">\r\n");
      out.write("\t\t<svg class=\"circular\" width=\"48px\" height=\"48px\">\r\n");
      out.write("\t\t<circle class=\"path-bg\" cx=\"24\" cy=\"24\" r=\"22\" fill=\"none\"\r\n");
      out.write("\t\t\tstroke-width=\"4\" stroke=\"#eeeeee\" />\r\n");
      out.write("\t\t<circle class=\"path\" cx=\"24\" cy=\"24\" r=\"22\" fill=\"none\"\r\n");
      out.write("\t\t\tstroke-width=\"4\" stroke-miterlimit=\"10\" stroke=\"#F96D00\" /></svg>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("  <!-- Modal -->\r\n");
      out.write("    <div class=\"modal fade\" id=\"exampleModal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"exampleModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("        <div class=\"modal-dialog\" role=\"document\">\r\n");
      out.write("            <div class=\"modal-content\">\r\n");
      out.write("                <div class=\"modal-header\">\r\n");
      out.write("                    <h4 class=\"modal-title\" id=\"exampleModalLabel\">특허 사용 허가 신청서</h4>\r\n");
      out.write("                    <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\r\n");
      out.write("                        <span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("                    </button>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"modal-body\">\r\n");
      out.write("                    <form  id=\"permitionForm\" >\r\n");
      out.write("                        <div class=\"form-group\">\r\n");
      out.write("                            <label for=\"appointment_date\" class=\"text-black\"><b>신청일</b></label>\r\n");
      out.write("                            <input type=\"text\" class=\"form-control\" name=\"contractDate\" id=\"contractDate\" value=\"\" placeholder=\"\" readonly=\"readonly\">\r\n");
      out.write("                            <input type=\"hidden\" name=\"itemNum\" id=\"itNum\" value=\"\"  /> \r\n");
      out.write("                             <input type=\"hidden\" name=\"DocumentNum\" id=\"DocumentNum\" value=\"\"  /> \r\n");
      out.write("                              \r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"form-group\">\r\n");
      out.write("                        <input type=\"hidden\" name=\"PTI_seq\" id=\"Pti_seq\" value=\"\"  /> \r\n");
      out.write("                            <label for=\"appointment_name\" class=\"text-black\"><b>신청인</b></label>\r\n");
      out.write("                            <input type=\"text\" class=\"form-control\" name=\"memberId\" id=\"memberId\" value=\"\" placeholder=\"\" readonly=\"readonly\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"form-group\">\r\n");
      out.write("                            <label for=\"appointment_patentnum\" class=\"text-black\"><b>특허번호</b></label>\r\n");
      out.write("                            <input type=\"text\" class=\"form-control\" name=\"patentNum\" id=\"patentNum\" value=\"\" placeholder=\"\" readonly=\"readonly\">\r\n");
      out.write("                       \t\t\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"row\">\r\n");
      out.write("                            <div class=\"col-md-6\">\r\n");
      out.write("                                <div class=\"form-group\">\r\n");
      out.write("                                    <a href=\"#\" class=\"a_document\" id=\"down\"></a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"col-md-6\">\r\n");
      out.write("                                <div class=\"form-group\">\r\n");
      out.write("                                    <a href=\"#\" class=\"a_document\" id=\"down1\"></a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"form-group\">\r\n");
      out.write("                            <label for=\"appointment_file\" class=\"text-black\"><b>[보유자]특허 사용 신청서 / 허가서</b></label>\r\n");
      out.write("                            <input type=\"file\" class=\"form-control\" name=\"upload\" id=\"upload\" multiple>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </form>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"modal-footer\">\r\n");
      out.write("                    <button type=\"button\" id=\"permitBtn\" class=\"btn btn-outline-info\">승인하기</button>\r\n");
      out.write("                    <button type=\"button\" class=\"btn btn-outline-success\" data-dismiss=\"modal\">닫기</button>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("\t<script src=\"/cloud/resources/js/jquery.min.js\"></script>\r\n");
      out.write("\t<script src=\"/cloud/resources/js/jquery-migrate-3.0.1.min.js\"></script>\r\n");
      out.write("\t<script src=\"/cloud/resources/js/popper.min.js\"></script>\r\n");
      out.write("\t<script src=\"/cloud/resources/js/bootstrap.min.js\"></script>\r\n");
      out.write("\t<script src=\"/cloud/resources/js/jquery.easing.1.3.js\"></script>\r\n");
      out.write("\t<script src=\"/cloud/resources/js/jquery.waypoints.min.js\"></script>\r\n");
      out.write("\t<script src=\"/cloud/resources/js/jquery.stellar.min.js\"></script>\r\n");
      out.write("\t<script src=\"/cloud/resources/js/owl.carousel.min.js\"></script>\r\n");
      out.write("\t<script src=\"/cloud/resources/js/jquery.magnific-popup.min.js\"></script>\r\n");
      out.write("\t<script src=\"/cloud/resources/js/aos.js\"></script>\r\n");
      out.write("\t<script src=\"/cloud/resources/js/jquery.animateNumber.min.js\"></script>\r\n");
      out.write("\t<script src=\"/cloud/resources/js/scrollax.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<script src=\"/cloud/resources/js/main.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("<footer class=\"ftco-footer ftco-section\">\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("\t<div class=\"row mb-5\">\r\n");
      out.write("\t\t<div class=\"col-md\">\r\n");
      out.write("\t\t\t<div class=\"ftco-footer-widget mb-4\">\r\n");
      out.write("\t\t\t\t<h2 class=\"ftco-heading-2\">\r\n");
      out.write("\t\t\t\t\tAbout <span>Neutral</span>\r\n");
      out.write("\t\t\t\t</h2>\r\n");
      out.write("\t\t\t\t<p>Far far away, behind the word mountains, far from the\r\n");
      out.write("\t\t\t\t\tcountries Vokalia and Consonantia, there live the blind texts.</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"col-md\">\r\n");
      out.write("\t\t\t<div class=\"ftco-footer-widget mb-4 ml-md-4\">\r\n");
      out.write("\t\t\t\t<h2 class=\"ftco-heading-2\">Links</h2>\r\n");
      out.write("\t\t\t\t<ul class=\"list-unstyled\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\"><span class=\"icon-long-arrow-right mr-2\"></span>Home</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\"><span class=\"icon-long-arrow-right mr-2\"></span>About</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\"><span class=\"icon-long-arrow-right mr-2\"></span>Practice\r\n");
      out.write("\t\t\t\t\t\t\tAreas</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\"><span class=\"icon-long-arrow-right mr-2\"></span>Attorneys</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\"><span class=\"icon-long-arrow-right mr-2\"></span>Blog</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\"><span class=\"icon-long-arrow-right mr-2\"></span>Contact</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"col-md\">\r\n");
      out.write("\t\t\t<div class=\"ftco-footer-widget mb-4\">\r\n");
      out.write("\t\t\t\t<h2 class=\"ftco-heading-2\">Practice Areas</h2>\r\n");
      out.write("\t\t\t\t<ul class=\"list-unstyled\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\"><span class=\"icon-long-arrow-right mr-2\"></span>Family\r\n");
      out.write("\t\t\t\t\t\t\tLaw</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\"><span class=\"icon-long-arrow-right mr-2\"></span>Business\r\n");
      out.write("\t\t\t\t\t\t\tLaw</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\"><span class=\"icon-long-arrow-right mr-2\"></span>Insurance\r\n");
      out.write("\t\t\t\t\t\t\tLaw</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\"><span class=\"icon-long-arrow-right mr-2\"></span>Criminal\r\n");
      out.write("\t\t\t\t\t\t\tLaw</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\"><span class=\"icon-long-arrow-right mr-2\"></span>Drug\r\n");
      out.write("\t\t\t\t\t\t\tOffenses</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\"><span class=\"icon-long-arrow-right mr-2\"></span>Property\r\n");
      out.write("\t\t\t\t\t\t\tLaw</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\"><span class=\"icon-long-arrow-right mr-2\"></span>Employment\r\n");
      out.write("\t\t\t\t\t\t\tLaw</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"col-md\">\r\n");
      out.write("\t\t\t<div class=\"ftco-footer-widget mb-4\">\r\n");
      out.write("\t\t\t\t<h2 class=\"ftco-heading-2\">Have a Questions?</h2>\r\n");
      out.write("\t\t\t\t<div class=\"block-23 mb-0\">\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t<li><span class=\"icon icon-map-marker\"></span><span\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"text\">203 Fake St. Mountain View, San Francisco,\r\n");
      out.write("\t\t\t\t\t\t\t\tCalifornia, USA</span></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\"><span class=\"icon icon-phone\"></span><span\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"text\">+2 392 3929 210</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\"><span class=\"icon icon-envelope\"></span><span\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"text\">info@yourdomain.com</span></a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<ul\r\n");
      out.write("\t\t\t\t\tclass=\"ftco-footer-social list-unstyled float-md-left float-lft mt-4\">\r\n");
      out.write("\t\t\t\t\t<li class=\"ftco-animate\"><a href=\"#\"><span\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"icon-twitter\"></span></a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"ftco-animate\"><a href=\"#\"><span\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"icon-facebook\"></span></a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"ftco-animate\"><a href=\"#\"><span\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"icon-instagram\"></span></a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("</footer>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/patent/patent_use_list.jsp(174,5) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.loginId==null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t          <li style=\"margin-left: 20px; \" class=\"nav-item cta\"><a href=\"/cloud/member/gologin\" class=\"nav-link\" data-toggle=\"modal\" data-target=\"#modalAppointment\" style=\"text-decoration: none;\">로그인</a></li>\r\n");
          out.write("              <li style=\"margin-left: 20px;\" class=\"nav-item cta\"><a href=\"/cloud/member/gosign\" class=\"nav-link\" data-toggle=\"modal\" data-target=\"#modalAppointment\" style=\"text-decoration: none;\">회원가입</a></li>\r\n");
          out.write("\t\t\t  ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /WEB-INF/views/patent/patent_use_list.jsp(178,5) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.loginId!=null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t          <li class=\"nav-item\"><a href=\"/cloud/member/goMypage\" class=\"nav-link\"><span>마이페이지</span></a></li>\r\n");
          out.write("\t\t\t  <li style=\"margin-left: 20px;\" class=\"nav-item cta\"><a class=\"nav-link\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.loginName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write(' ');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.loginType}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("님 </a></li>\r\n");
          out.write("\t\t\t  <li style=\"margin-left: 20px;\" class=\"nav-item cta\"><a href=\"/cloud/member/logout\" class=\"nav-link\">로그아웃</a></li>\r\n");
          out.write("\t          ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/views/patent/patent_use_list.jsp(242,4) name = varStatus type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVarStatus("status");
      // /WEB-INF/views/patent/patent_use_list.jsp(242,4) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("pat");
      // /WEB-INF/views/patent/patent_use_list.jsp(242,4) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/patent/patent_use_list.jsp(242,4) '${pList}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t\t<tr class= \"del\" >\r\n");
            out.write("\t\t\t\t<th scope=\"row\" name=\"\" >");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${status.count}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</th>\r\n");
            out.write("\t\t\t\t<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pat.patenttype}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("\t\t\t\t<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pat.patentName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("\t\t\t\t<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pat.memberGo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("\t\t\t\t<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pat.contractDate}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("\t\t\t\t<td><button type=\"button\" class=\"pri\" data-member=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pat.memberGo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" data-value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pat.patentNum}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" data-id=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pat.itemNum}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" data-name=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pat.documentNum}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\"  value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pat.PTI_seq}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\"  data-toggle=\"modal\" data-target=\"#exampleModal\" data-contractDate=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pat.contractDate }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(">상세보기\t\r\n");
            out.write("\t\t\t\t</button></td>\r\n");
            out.write("\t\t\t\t</tr>\t\t\t\t\t\t\t\t<!-- data-id= \"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${memberId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" -->\r\n");
            out.write("\t\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }
}
