/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.21
 * Generated at: 2019-10-08 14:40:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Mypage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1562034500000L));
    _jspx_dependants.put("jar:file:/C:/Users/창민/Documents/GitHub/GoodDeV/ChanMin/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/GoodDeV/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <title>SupporterS :: My Page</title>\r\n");
      out.write("\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, minimum-scale=1.0\">\r\n");
      out.write("    \r\n");
      out.write(" \t<!-- jquery 우선 실행 -->\r\n");
      out.write(" \t\r\n");
      out.write("\t<script src=\"/cloud/resources/js/jquery-3.4.1.min.js\"></script>\r\n");
      out.write("    <script src=\"/cloud/resources/js/jquery-ui.min.js\"></script>\r\n");
      out.write("\t<!-- <script src=\"/cloud/resources/js/list.js\"></script> -->\r\n");
      out.write("    \r\n");
      out.write("    <!-- Tap 기능 jquery 실행 -->\r\n");
      out.write("    <script src=\"/cloud/resources/js/ef-tabs.js\"></script>\r\n");
      out.write("    <script src=\"/cloud/resources/js/jquery.transit.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("\t<!-- bootstrap 포함 css 순차 실행 -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/cloud/resources/css/open-iconic-bootstrap.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/cloud/resources/css/animate.css\">\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/cloud/resources/css/owl.carousel.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/cloud/resources/css/owl.theme.default.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/cloud/resources/css/magnific-popup.css\">\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/cloud/resources/css/aos.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/cloud/resources/css/ionicons.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/cloud/resources/css/flaticon.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/cloud/resources/css/icomoon.css\">\r\n");
      out.write("    \r\n");
      out.write("    <!-- Tap + Personal CSS/JS -->\r\n");
      out.write("   \r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/cloud/resources/css/style.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/cloud/resources/css/Board.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/cloud/resources/css/demo.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/cloud/resources/css/ef-tabs.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/cloud/resources/css/ef-tabs-light-blue.css\">\r\n");
      out.write("\r\n");
      out.write("    <script>  \r\n");
      out.write("$(function(){\r\n");
      out.write("\t\t\tboardList();\r\n");
      out.write("\r\n");
      out.write("        \t$('#patentList').on('click', function() {\t\r\n");
      out.write("            \t\tpatent();\r\n");
      out.write("       \t\t})\r\n");
      out.write("\t\t\t\r\n");
      out.write("            $('#itemList').on('click',function(){\r\n");
      out.write("            \titem();\r\n");
      out.write("       \t\t})\t\r\n");
      out.write("       \t\t\r\n");
      out.write("            \r\n");
      out.write("            $('#shape-survey').on('click', function() {\r\n");
      out.write("            \tservey();\r\n");
      out.write("            })\r\n");
      out.write("    \r\n");
      out.write("             $('#shape-qna').on('click', function() {\r\n");
      out.write("            \t boardList();\r\n");
      out.write("            })\r\n");
      out.write("            \r\n");
      out.write("             $('#shape-funding').on('click', function() {\r\n");
      out.write("\t\t\t\t fundList();\r\n");
      out.write("            })\r\n");
      out.write("            \r\n");
      out.write("});\r\n");
      out.write("function patent(){   \r\n");
      out.write("\tvar pageSu;\r\n");
      out.write("    $(function(){\r\n");
      out.write(" \t\t   pageSu = 9;\r\n");
      out.write(" \t\t   patentTable(pageSu);   \r\n");
      out.write("\r\n");
      out.write("    });\r\n");
      out.write("    \r\n");
      out.write("    jQuery(document).on('click', '#rightBtn', function(){\r\n");
      out.write(" \t   \t\t\tpageSu += 10;\r\n");
      out.write(" \t   \t\t\t$.ajax({\r\n");
      out.write(" \t   \t\t\t\turl: 'patentSu',\r\n");
      out.write(" \t   \t\t\t\ttype : 'get',\r\n");
      out.write(" \t   \t\t\t\tsuccess : function(res){\r\n");
      out.write(" \t   \t\t\t\t\tif(pageSu<res){\r\n");
      out.write(" \t   \t\t\t\t\t\tpatentTable(pageSu); \r\n");
      out.write(" \t   \t\t\t\t\t}else {\r\n");
      out.write(" \t   \t\t\t\t\t\tpageSu = 9;\r\n");
      out.write(" \t   \t\t\t\t\t\tpatentTable(pageSu);\r\n");
      out.write(" \t   \t\t\t\t\t\t//ex) 172개 일때, 170개는 보여지지만 2개는 아직 안보임;;\r\n");
      out.write(" \t   \t\t\t\t\t}\r\n");
      out.write(" \t   \t\t\t\t}\r\n");
      out.write(" \t   \t\t\t})\r\n");
      out.write(" \t   }); \r\n");
      out.write("    \r\n");
      out.write("    jQuery(document).on('click', '#leftBtn', function(){\r\n");
      out.write(" \t \t  \t\t\r\n");
      out.write(" \t   \t\t\tpageSu -= 10;\r\n");
      out.write(" \t \t\r\n");
      out.write(" \t \t  \t\tif(pageSu>0){\r\n");
      out.write(" \t \t  \t\t\tpatentTable(pageSu); \r\n");
      out.write(" \t \t  \t\t}else{\r\n");
      out.write(" \t \t  \t\t\tpageSu = 9;\r\n");
      out.write(" \t \t  \t\t\talert('응 첫페이지..');\r\n");
      out.write(" \t \t  \t\t\tpatentTable(pageSu); \r\n");
      out.write(" \t \t  \t\t}\r\n");
      out.write(" \t \t  \t\t\r\n");
      out.write(" });\r\n");
      out.write("    \r\n");
      out.write("  \r\n");
      out.write("   \r\n");
      out.write("    function patentTable(pageSu){\r\n");
      out.write(" \t\r\n");
      out.write(" \t   $.ajax({\r\n");
      out.write(" \t   \t\turl : 'patentTable',\r\n");
      out.write(" \t   \t\ttype : 'get',\r\n");
      out.write(" \t   \t\tdata : {\r\n");
      out.write(" \t   \t\t\tpageSu : pageSu\r\n");
      out.write(" \t   \t\t},\r\n");
      out.write(" \t   \t\tsuccess : output\t   \t\t\r\n");
      out.write(" \t   \t})\r\n");
      out.write(" \t   \r\n");
      out.write(" \t   \r\n");
      out.write("    }\r\n");
      out.write("    function output(res){\r\n");
      out.write(" \t   \tvar tag = '';\r\n");
      out.write("        tag += '<table class=\"pTable\">'\r\n");
      out.write("        tag += '<caption class=\"table_title\"><b>보유 및 사용 중인 특허 목록</b></caption>'\r\n");
      out.write("        tag += '<thead class=\"navy\">' \r\n");
      out.write("        tag += '<tr>'   \r\n");
      out.write("        tag += '<th scope=\"col\">No.</th>'        \r\n");
      out.write("        tag += '<th scope=\"col\">분류</th>'       \r\n");
      out.write("        tag += '<th scope=\"col\">특허명</th>'    \r\n");
      out.write("        tag += '<th scope=\"col\">특허 보유자</th>'    \r\n");
      out.write("   \t    tag += '<th scope=\"col\">등록날짜</th>'    \r\n");
      out.write("   \t    tag += '</tr>'\r\n");
      out.write("    \ttag += '</thead>' \r\n");
      out.write("    \ttag += '<tbody>'  \r\n");
      out.write("\t   $.each(res,function(i,item){\r\n");
      out.write("\t\t   \t\tvar patentNum = item.patentNum;\r\n");
      out.write("\t\t   \t\tvar patenttype = item.patenttype;\r\n");
      out.write("\t\t   \t\tvar patentName = item.patentName;\r\n");
      out.write("\t\t   \t\tvar patentContent = item.patentContent;\r\n");
      out.write("\t\t   \t\tvar patentHolderName = item.patentHolderName;\r\n");
      out.write("\t\t   \t\t\r\n");
      out.write("\r\n");
      out.write("\t\t   \t\tif (patentNum.length >= 10) {\r\n");
      out.write("\t\t   \t\t                  //patentNum = patentNum.split(\"-\",2)+\"...\";\r\n");
      out.write("\t\t   \t\t                  patentNum = patentNum.substr(0, 10) + \"...\";\r\n");
      out.write("\t\t   \t\t                  tag += '<th scope=\"row\" name=\"특허번호\"><a class=\"lcm\" data-id=\"'+item.patentNum+'\">' + patentNum + '</a></th>'\r\n");
      out.write("\t\t   \t\t              }  else {\r\n");
      out.write("\t\t   \t\t                  tag += '<th scope=\"row\" name=\"특허번호\"><a class=\"lcm\" data-id=\"'+item.patentNum+'\">' + patentNum + '</a></th>'\r\n");
      out.write("\t\t   \t\t              }\r\n");
      out.write("              \r\n");
      out.write("              if (patenttype == null) {\r\n");
      out.write("                  //patenttype = patenttype.substr(0,7)+\"...\";\r\n");
      out.write("                  tag += '<td name=\"분류\" >' + '' + '</td>'\r\n");
      out.write("              } else if(patenttype.length >= 8 ){\r\n");
      out.write("                 tag += '<td name=\"분류\" >' + patenttype + '</td>'\r\n");
      out.write("              }\r\n");
      out.write("              \r\n");
      out.write("              if (patentName==null) {\r\n");
      out.write("                 tag += '<td name=\"특허명\"><b>' + '' + '</b></td>'\r\n");
      out.write("              } else if(patentName.length >= 15){\r\n");
      out.write("                  patentName = patentName.substr(0, 24) + \"...\";\r\n");
      out.write("                   tag += '<td name=\"특허명\"><b>' + patentName.split(\"(\", 1) + '</b></td>'\r\n");
      out.write("              }else{\r\n");
      out.write("                 tag += '<td name=\"특허명\"><b>' + patentName + '</b></td>'\r\n");
      out.write("              }\r\n");
      out.write("              /* if(patentContent.length >= 20){\r\n");
      out.write("                 patentContent = patentContent.substr(0,40)+\"...\";\r\n");
      out.write("                  tag += '<td name=\"특허설명\" ><b>'+patentContent+'</b></td>'\r\n");
      out.write("              } */\r\n");
      out.write("              if (patentHolderName.length >= 5) {\r\n");
      out.write("                  patentHolderName = patentHolderName.substr(0, 4) + \"...\";\r\n");
      out.write("                  tag += '<td name=\"특허 보유자\" >' + patentHolderName + '</td>'\r\n");
      out.write("              } else {\r\n");
      out.write("                 tag += '<td name=\"특허 보유자\" >' + patentHolderName + '</td>'\r\n");
      out.write("              }\r\n");
      out.write("             /*  else {\r\n");
      out.write("                  tag += '<tr>'\r\n");
      out.write("                  tag += '<th scope=\"row\" name=\"특허번호\">' + patentNum + '</th>'\r\n");
      out.write("                  tag += '<td name=\"분류\" >' + patenttype + '</td>'\r\n");
      out.write("                  tag += '<td name=\"특허명\" ><b>' + patentName + '</b></td>'\r\n");
      out.write("                  /* tag += '<td name=\"특허설명\" ><b>'+patentContent+'</b></td>' \r\n");
      out.write("                  tag += '<td name=\"특허 보유자\" >' + patentHolderName + '</td>'\r\n");
      out.write("              } */\r\n");
      out.write("\r\n");
      out.write("              if (item.patentRegDate != null) {\r\n");
      out.write("                  tag += '<td name=\"등록날짜\">' + item.patentRegDate + '</td>'\r\n");
      out.write("              } else {\r\n");
      out.write("                  tag += '<td >[등록진행중]</td>'\r\n");
      out.write("              }\r\n");
      out.write("\r\n");
      out.write("          \r\n");
      out.write("              //인터셉터 처리\r\n");
      out.write("              tag += '</tr>'\r\n");
      out.write("          })\r\n");
      out.write("    \t   \ttag += '</tbody>'\t\r\n");
      out.write("    \t    tag += '</table>' \r\n");
      out.write("    \t\ttag += '<div class=\"tri-btn\">'\r\n");
      out.write("    \t\ttag += '<button id=\"leftBtn\" class=\"btn btn-primary\">◀</button>'\t\r\n");
      out.write("    \t    tag += '<button id=\"rightBtn\" class=\"btn btn-primary\">▶</button>'\t\r\n");
      out.write("    \t    tag +=\t'</div>'\r\n");
      out.write("        $('#section-bar-patent').html(tag);\r\n");
      out.write("    \t$('.lcm').on('click',pop);    \r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function pop(){\r\n");
      out.write("\tvar patentNum = $(this).attr('data-id');\r\n");
      out.write("\t// window.open(\"/cloud/funding/fundingChat?crowdfundingNum=\"+crowdfundingNum, \"PopupWin\", \"width=800,height=700\");\r\n");
      out.write("\twindow.open(\"/cloud/patent/patentDetail?patentNum=\"+patentNum,\"PopupWin\",\"width=800,height=700\")\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function item(){\r\n");
      out.write("\tvar pageSu;\r\n");
      out.write("    $(function(){\r\n");
      out.write(" \t\t   pageSu = 9;\r\n");
      out.write(" \t\t   itemTable(pageSu);   \r\n");
      out.write("\r\n");
      out.write("    });\r\n");
      out.write("    \r\n");
      out.write("    jQuery(document).on('click', '#riBtn', function(){\r\n");
      out.write(" \t   \t\t\tpageSu += 10;\r\n");
      out.write(" \t   \t\t\talert(pageSu);\r\n");
      out.write(" \t   \t\t\t$.ajax({\r\n");
      out.write(" \t   \t\t\t\turl: 'itemSu',\r\n");
      out.write(" \t   \t\t\t\ttype : 'get',\r\n");
      out.write(" \t   \t\t\t\tsuccess : function(res){\r\n");
      out.write(" \t   \t\t\t\t\tif(pageSu<res){\r\n");
      out.write(" \t   \t\t\t\t\titemTable(pageSu); \r\n");
      out.write(" \t   \t\t\t\t\t}else {\r\n");
      out.write(" \t   \t\t\t\t\t\tpageSu = 9;\r\n");
      out.write(" \t   \t\t\t\t\titemTable(pageSu);\r\n");
      out.write(" \t   \t\t\t\t\t\t//ex) 172개 일때, 170개는 보여지지만 2개는 아직 안보임;;\r\n");
      out.write(" \t   \t\t\t\t\t}\r\n");
      out.write(" \t   \t\t\t\t}\r\n");
      out.write(" \t   \t\t\t})\r\n");
      out.write(" \t   }); \r\n");
      out.write("    \r\n");
      out.write("    jQuery(document).on('click', '#leBtn', function(){\r\n");
      out.write(" \t \t  \t\t\r\n");
      out.write(" \t   \t\t\tpageSu -= 10;\r\n");
      out.write(" \t \t\r\n");
      out.write(" \t \t  \t\tif(pageSu>0){\r\n");
      out.write(" \t \t  \t\titemTable(pageSu); \r\n");
      out.write(" \t \t  \t\t}else{\r\n");
      out.write(" \t \t  \t\t\tpageSu = 9;\r\n");
      out.write(" \t \t  \t\t\talert('응 첫페이지..');\r\n");
      out.write(" \t \t  \t\titemTable(pageSu); \r\n");
      out.write(" \t \t  \t\t}\r\n");
      out.write(" \t \t  \t\t\r\n");
      out.write(" });\r\n");
      out.write("    \r\n");
      out.write("    jQuery(\"#section-bar-item\").on('click', '#itemSign', function(){\r\n");
      out.write("   \t \t\twindow.location.href=\"/cloud/item/goItemWrite\";\t\t\r\n");
      out.write("});\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("   \r\n");
      out.write("    function itemTable(pageSu){\r\n");
      out.write(" \t \r\n");
      out.write(" \t   $.ajax({\r\n");
      out.write(" \t   \t\turl : 'itemTable',\r\n");
      out.write(" \t   \t\ttype : 'get',\r\n");
      out.write(" \t   \t\tdata : {\r\n");
      out.write(" \t   \t\t\tpageSu : pageSu\r\n");
      out.write(" \t   \t\t},\r\n");
      out.write(" \t   \t\tsuccess : output\t   \t\t\r\n");
      out.write(" \t   \t})\r\n");
      out.write(" \t   \r\n");
      out.write(" \t   \r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("  \r\n");
      out.write("    function output(res){\r\n");
      out.write(" \t   var tag = '';\r\n");
      out.write("        tag += '<table class=\"iTable\">'\r\n");
      out.write("        tag += '<caption class=\"table_title\"><b>시제품 및 출시품 목록</b></caption>'\r\n");
      out.write("        tag += '<div class=\"cap-btn\">'\r\n");
      out.write("        tag += '<a href=\"#\" id=\"itemSign\" class=\"btns btn3\" style=\"margin-right : 30px;\">제품 등록</a>'\r\n");
      out.write("        tag += '<a href=\"/cloud/item/goItemHistory\"  class=\"btns btn-3-comments\">제품 수정 기록 보기</a>'\r\n");
      out.write("        tag += '</div>'\r\n");
      out.write("        tag += '<thead class=\"navy\">' \r\n");
      out.write("        tag += '<tr>'   \r\n");
      out.write("        tag += '<th scope=\"col\" style=\"text-align:center;\">Item No.</th>'        \r\n");
      out.write("        tag += '<th scope=\"col\">분류</th>'       \r\n");
      out.write("        tag += '<th scope=\"col\">제품명</th>'    \r\n");
      out.write("        tag += '<th scope=\"col\">제품 설명</th>'     \r\n");
      out.write("   \t    tag += '</tr>'\r\n");
      out.write("   \t    tag += '</thead>' \r\n");
      out.write("    \ttag += '<tbody>'\r\n");
      out.write("    \t   $.each(res,function(i,item){\r\n");
      out.write("    \t\tif(item.itemType != 'none'){   \r\n");
      out.write(" \t   \t   \ttag += '<tr>'\r\n");
      out.write(" \t   \t  \ttag += '<th scope=\"row\" name=\"아이템번호\">'+item.itemNum+'</th>'        \r\n");
      out.write("    \t   \t\ttag += '<td name=\"분류\">' + item.itemType + '</td>'\r\n");
      out.write("    \t   \t\ttag += '<td name=\"제품명\"><a href=\"/cloud/item/goItemDetail?itemNum='+item.itemNum+'\" class=\"mypage-link\">' + item.itemName + '</a></td>'\r\n");
      out.write("    \t   \t\ttag += '<td name=\"제품 내용\">'+item.itemContent+'</td>'\r\n");
      out.write("    \t   \t\ttag += '</tr>'\r\n");
      out.write("    \t\t}\r\n");
      out.write("    \t   \t})\r\n");
      out.write("    \t   \r\n");
      out.write("    \t   \ttag += '</tbody>'\t\r\n");
      out.write("    \t\ttag += '</table>' \r\n");
      out.write("    \t\ttag += '<div class=\"tri-btn\">'\r\n");
      out.write("    \t   \ttag += '<button id=\"leBtn\" class=\"btn btn-primary\">◀</button>'\t\r\n");
      out.write("    \t    tag += '<button id=\"riBtn\" class=\"btn btn-primary\">▶</button>'\t\r\n");
      out.write("\t        tag +='</div>'\r\n");
      out.write("        $('#section-bar-item').html(tag);\t\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function fund(){\r\n");
      out.write("\tvar pageSu;\r\n");
      out.write("    $(function(){\r\n");
      out.write(" \t\t   pageSu = 9;\r\n");
      out.write(" \t\t   patentTable(pageSu);   \r\n");
      out.write("\r\n");
      out.write("    });\r\n");
      out.write("    \r\n");
      out.write("    jQuery(document).on('click', '#', function(){\r\n");
      out.write(" \t   \t\t\tpageSu += 10;\r\n");
      out.write(" \t   \t\t\t$.ajax({\r\n");
      out.write(" \t   \t\t\t\turl: 'patentSu',\r\n");
      out.write(" \t   \t\t\t\ttype : 'get',\r\n");
      out.write(" \t   \t\t\t\tsuccess : function(res){\r\n");
      out.write(" \t   \t\t\t\t\tif(pageSu<res){\r\n");
      out.write(" \t   \t\t\t\t\t\tpatentTable(pageSu); \r\n");
      out.write(" \t   \t\t\t\t\t}else {\r\n");
      out.write(" \t   \t\t\t\t\t\tpageSu = 9;\r\n");
      out.write(" \t   \t\t\t\t\t\tpatentTable(pageSu);\r\n");
      out.write(" \t   \t\t\t\t\t\t//ex) 172개 일때, 170개는 보여지지만 2개는 아직 안보임;;\r\n");
      out.write(" \t   \t\t\t\t\t}\r\n");
      out.write(" \t   \t\t\t\t}\r\n");
      out.write(" \t   \t\t\t})\r\n");
      out.write(" \t   }); \r\n");
      out.write("    \r\n");
      out.write("    jQuery(document).on('click', '#', function(){\r\n");
      out.write(" \t \t  \t\t\r\n");
      out.write(" \t   \t\t\tpageSu -= 10;\r\n");
      out.write(" \t \t\r\n");
      out.write(" \t \t  \t\tif(pageSu>0){\r\n");
      out.write(" \t \t  \t\t\tpatentTable(pageSu); \r\n");
      out.write(" \t \t  \t\t}else{\r\n");
      out.write(" \t \t  \t\t\tpageSu = 9;\r\n");
      out.write(" \t \t  \t\t\talert('응 첫페이지..');\r\n");
      out.write(" \t \t  \t\t\tpatentTable(pageSu); \r\n");
      out.write(" \t \t  \t\t}\r\n");
      out.write(" \t \t  \t\t\r\n");
      out.write(" });\r\n");
      out.write("    \r\n");
      out.write("   \r\n");
      out.write("    function patentTable(pageSu){\r\n");
      out.write(" \t \r\n");
      out.write(" \t   $.ajax({\r\n");
      out.write(" \t   \t\turl : 'patentTable',\r\n");
      out.write(" \t   \t\ttype : 'get',\r\n");
      out.write(" \t   \t\tdata : {\r\n");
      out.write(" \t   \t\t\tpageSu : pageSu\r\n");
      out.write(" \t   \t\t},\r\n");
      out.write(" \t   \t\tsuccess : output\t   \t\t\r\n");
      out.write(" \t   \t})\r\n");
      out.write(" \t   \r\n");
      out.write(" \t   \r\n");
      out.write("    }\r\n");
      out.write("    function output(res){\r\n");
      out.write(" \t   var tag = '';\r\n");
      out.write("        tag += '<table class=\"fTable\">'\r\n");
      out.write("        tag += '<caption class=\"table_title\"><b>크라우드 펀딩 실시/투자 목록</b></caption>'\r\n");
      out.write("        tag += '<thead class=\"navy\">' \r\n");
      out.write("        tag += '<tr>'   \r\n");
      out.write("        tag += '<th scope=\"col\">No.</th>'        \r\n");
      out.write("        tag += '<th scope=\"col\">분류</th>'       \r\n");
      out.write("        tag += '<th scope=\"col\">제목</th>'    \r\n");
      out.write("        tag += '<th scope=\"col\">시작일</th>'    \r\n");
      out.write("        tag += '<th scope=\"col\">마감일</th>'        \r\n");
      out.write("   \t    tag += '</tr>'\r\n");
      out.write("   \t    tag += '</thead>' \r\n");
      out.write("    \ttag += '<tbody>'\r\n");
      out.write("    \t   $.each(res,function(i,item){\r\n");
      out.write(" \t   \t   \ttag += '<tr>'\r\n");
      out.write(" \t   \t  \ttag += '<th scope=\"row\" name=\"아이템번호\">'+item.d+'</th>'        \r\n");
      out.write("    \t   \t\ttag += '<td name=\"분류\">'+item.a+'</td>'\r\n");
      out.write("    \t   \t\ttag += '<td name=\"제목\">'+item.b+'</td>' //item.fundName 필요 ()\r\n");
      out.write("    \t   \t\ttag += '<td name=\"시작일\">'+item.b+'</td>'// item.시작일 \t==> 필요\r\n");
      out.write("    \t   \t\ttag += '<td name=\"마감일\">'+item.c+'</td>'\r\n");
      out.write("    \t   \t\ttag += '</tr>'\r\n");
      out.write("    \t   \t})\r\n");
      out.write("    \t   \r\n");
      out.write("    \t   tag += '</tbody>'\t\r\n");
      out.write("    \t   tag += '<tr><td>'\r\n");
      out.write("    \t   tag += '<button id=\"leftBtn\">◀</button>'\t\r\n");
      out.write("    \t   tag += '<button id=\"rightBtn\">▶</button>'\t\r\n");
      out.write("    \t   tag += '</td></tr>'\r\n");
      out.write("    \t   tag += '</table>' \r\n");
      out.write("    \r\n");
      out.write("        $('#section-bar-funding').html(tag);\t\r\n");
      out.write("    \t}\r\n");
      out.write("\t}\r\n");
      out.write("     \r\n");
      out.write("\r\n");
      out.write("function servey(){\r\n");
      out.write("\tvar pageSu;        \r\n");
      out.write("\t$(function(){\r\n");
      out.write("\t\t   pageSu = 9;\r\n");
      out.write("\t\t   serveyTable(pageSu);   \r\n");
      out.write("\r\n");
      out.write(" });\r\n");
      out.write("jQuery(document).on('click', '#rightBtn', function(){\r\n");
      out.write("\t\t\tpageSu += 10;\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl: '/cloud/servey/serveySu',\r\n");
      out.write("\t\t\t\ttype : 'get',\r\n");
      out.write("\t\t\t\tsuccess : function(res){\r\n");
      out.write("\t\t\t\t\tif(pageSu<res){\r\n");
      out.write("\t\t\t\t\t\tserveyTable(pageSu); \r\n");
      out.write("\t\t\t\t\t}else {\r\n");
      out.write("\t\t\t\t\t\tpageSu = 9;\r\n");
      out.write("\t\t\t\t\t\tserveyTable(pageSu);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t})\r\n");
      out.write("}); \r\n");
      out.write("\r\n");
      out.write("jQuery(document).on('click', '#leftBtn', function(){\r\n");
      out.write("  \t\t\r\n");
      out.write("\t\t\tpageSu -= 10;\r\n");
      out.write("\r\n");
      out.write("  \t\tif(pageSu>0){\r\n");
      out.write("  \t\t\tserveyTable(pageSu); \r\n");
      out.write("  \t\t}else{\r\n");
      out.write("  \t\t\tpageSu = 9;\r\n");
      out.write("  \t\t\talert('응 첫페이지..');\r\n");
      out.write("  \t\t\tserveyTable(pageSu); \r\n");
      out.write("  \t\t}\r\n");
      out.write("  \t\t\r\n");
      out.write("});\r\n");
      out.write("function serveyTable(pageSu){\t\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl : '/cloud/survey/getSurveyListById',\r\n");
      out.write("\t\t\ttype : 'get',\r\n");
      out.write("\t\t\tdata : {\r\n");
      out.write("\t\t\t\tpageSu : pageSu\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tsuccess : output\r\n");
      out.write("\t})\r\n");
      out.write("}\t\t\r\n");
      out.write("\r\n");
      out.write("function output(res){\r\n");
      out.write("\t\t\tvar tag = '';\r\n");
      out.write("\t\t\ttag += '<table class=\"table\">'\r\n");
      out.write("\t        tag += '<caption class=\"table_title\"><b>테스트 목록</b></caption>'\r\n");
      out.write("\t        tag += '<thead class=\"navy\">' \r\n");
      out.write("\t        tag += '<tr>'   \r\n");
      out.write("\t        tag += '<th scope=\"col\">No.</th>'        \r\n");
      out.write("\t        tag += '<th scope=\"col\">제목</th>'       \r\n");
      out.write("\t        tag += '<th scope=\"col\">시작일</th>'    \r\n");
      out.write("\t        tag += '<th scope=\"col\">마감일</th>'    \r\n");
      out.write("\t   \t    tag += '</tr>'\r\n");
      out.write("\t    \ttag += '</thead>' \r\n");
      out.write("\t    \ttag += '<tbody>'  \r\n");
      out.write("\t\t\t$.each(res, function(i, item) {\r\n");
      out.write("\t\t\ti+=1;\r\n");
      out.write("\t\t\ttag += '<tr>'\r\n");
      out.write("\t\t\ttag += '<th scope=\"row\" >'+i+'</th>'\r\n");
      out.write("\t\t\ttag += '<td name=\"questionTitle\"><a class=\"mypage-link\" href=\"/cloud/survey/gosurvey_result?questionTimeNum='+item.questionTimeNum+'\">'+item.questionTitle+'</a></td>'\r\n");
      out.write("\t\t\ttag += '<td name=\"startDate\"><a class=\"mypage-link\" href=\"/cloud/survey/gosurvey_result?questionTimeNum='+item.questionTimeNum+'\">'+item.startDate+'</td>';\r\n");
      out.write("\t\t\ttag += '<td name=\"dueDate\"><a class=\"mypage-link\" href=\"/cloud/survey/gosurvey_result?questionTimeNum='+item.questionTimeNum+'\">'+item.dueDate+'</td>';\r\n");
      out.write("\t\t\ttag += '</tr>';\r\n");
      out.write("\t\t\t\t})\r\n");
      out.write("\t\t\ttag += '</tbody>'  \r\n");
      out.write("\t\t\ttag += '</table>'\r\n");
      out.write("\t\t\ttag += '<div class=\"tri-btn\">'\r\n");
      out.write("\t\t    tag += '<button id=\"leftBtn\" class=\"btn btn-primary\">◀</button>'\t\r\n");
      out.write("\t\t   \ttag += '<button id=\"rightBtn\" class=\"btn btn-primary\">▶</button>'\t\r\n");
      out.write("\t\t    tag += '</div>'\r\n");
      out.write("\t\t\t$('#section-bar-survey').html(tag);\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function boardList(){\r\n");
      out.write("\tvar pageSu;        \r\n");
      out.write("\t$(function(){\r\n");
      out.write("\t\t   pageSu = 9;\r\n");
      out.write("\t\t   boardTable(pageSu);   \r\n");
      out.write("\r\n");
      out.write(" });\r\n");
      out.write("\t\r\n");
      out.write("\t jQuery(document).on('click', '#rightBtn', function(){\r\n");
      out.write(" \t\t\tpageSu += 10;\r\n");
      out.write(" \t\t\t$.ajax({\r\n");
      out.write(" \t\t\t\turl: '/cloud/board/boardsu',\r\n");
      out.write(" \t\t\t\ttype : 'get',\r\n");
      out.write(" \t\t\t\tsuccess : function(res){\r\n");
      out.write(" \t\t\t\t\tif(pageSu<res){\r\n");
      out.write(" \t\t\t\t\t\tboardTable(pageSu); \r\n");
      out.write(" \t\t\t\t\t}else {\r\n");
      out.write(" \t\t\t\t\t\tpageSu = 9;\r\n");
      out.write(" \t\t\t\t\t\tboardTable(pageSu);\r\n");
      out.write(" \t\t\t\t\t}\r\n");
      out.write(" \t\t\t\t}\r\n");
      out.write(" \t\t\t})\r\n");
      out.write(" }); \r\n");
      out.write("\r\n");
      out.write("jQuery(document).on('click', '#leftBtn', function(){\r\n");
      out.write("\t  \t\t\r\n");
      out.write(" \t\t\tpageSu -= 10;\r\n");
      out.write("\t\r\n");
      out.write("\t  \t\tif(pageSu>0){\r\n");
      out.write("\t  \t\t\tboardTable(pageSu); \r\n");
      out.write("\t  \t\t}else{\r\n");
      out.write("\t  \t\t\tpageSu = 9;\r\n");
      out.write("\t  \t\t\talert('응 첫페이지..');\r\n");
      out.write("\t  \t\t\tboardTable(pageSu); \r\n");
      out.write("\t  \t\t}\r\n");
      out.write("\t  \t\t\r\n");
      out.write("});\r\n");
      out.write("function boardTable(pageSu){\r\n");
      out.write(" \t\r\n");
      out.write("\t   $.ajax({\r\n");
      out.write("\t   \t\turl : '/cloud/board/userboard',\r\n");
      out.write("\t   \t\ttype : 'get',\r\n");
      out.write("\t   \t\tdata : {\r\n");
      out.write("\t   \t\t\tpageSu : pageSu\r\n");
      out.write("\t   \t\t},\r\n");
      out.write("\t   \t\tsuccess : output\t   \t\t\r\n");
      out.write("\t   \t})\r\n");
      out.write("\t   \r\n");
      out.write("\t   \r\n");
      out.write(" }\r\n");
      out.write("function output(res){\r\n");
      out.write("\t\t\tvar tag = '';            \r\n");
      out.write("        \ttag += '<table class=\"table\">'\r\n");
      out.write("        \ttag += '<caption class=\"table_title\"><b>게시글 목록</b></caption>'\r\n");
      out.write("\t        tag += '<thead class=\"navy\">' \r\n");
      out.write("\t        tag += '<tr>'   \r\n");
      out.write("\t        tag += '<th scope=\"col\">No.</th>'        \r\n");
      out.write("\t        tag += '<th scope=\"col\">제목</th>'       \r\n");
      out.write("\t        tag += '<th scope=\"col\">작성일</th>'    \r\n");
      out.write("\t        tag += '<th scope=\"col\">카테고리</th>'       \r\n");
      out.write("\t   \t    tag += '</tr>'\r\n");
      out.write("\t    \ttag += '</thead>' \r\n");
      out.write("\t    \ttag += '<tbody class=\"boardTbody\" >'  \r\n");
      out.write("\t    \t$.each(res, function(i, item){\r\n");
      out.write("               i += 1;\r\n");
      out.write("               tag += '<tr>';\r\n");
      out.write("               tag += '<th scope=\"row\" name=\"boardNum\">' + i + '</th>'\r\n");
      out.write("               tag += '<td name=\"title\"><a class=\"mypage-link\" href=\"/cloud/board/boardDetail?boardNum=' + item.boardNum + '\">' + item.title + '</td>';\r\n");
      out.write("               tag += '<td name=\"boardDate\"><a class=\"mypage-link\" href=\"/cloud/board/boardDetail?boardNum=' + item.boardNum + '\">' + item.boardDate + '</a></td>';\r\n");
      out.write("               tag += '<td name=\"qType\"><a class=\"mypage-link\" href=\"/cloud/board/boardDetail?boardNum=' + item.boardNum + '\">' + item.qCategory + '</td>';\r\n");
      out.write("               tag += '</tr>'\r\n");
      out.write("    \t\t})\r\n");
      out.write("    \t\ttag += '</tbody>'\t\r\n");
      out.write("    \t    tag += '</table>' \r\n");
      out.write("    \t\ttag += '<div class=\"tri-btn\">'\r\n");
      out.write("    \t\ttag += '<button id=\"leftBtn\" class=\"btn btn-primary\">◀</button>'\t\r\n");
      out.write("    \t    tag += '<button id=\"rightBtn\" class=\"btn btn-primary\">▶</button>'\t\r\n");
      out.write("    \t    tag += '</div>'\r\n");
      out.write("    \t    $('#section-bar-qna').html(tag);\r\n");
      out.write("\t\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function fundList(){\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl : '/cloud/funding/myfundList',\r\n");
      out.write("\t\t\ttype : 'get',\r\n");
      out.write("\t\t\tsuccess : outputFunding\r\n");
      out.write("\t\t})\r\n");
      out.write("}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("   \tfunction outputFunding(res) {\r\n");
      out.write("            var tag = '';\r\n");
      out.write("            tag += '<table class=\"table\">'    \r\n");
      out.write("            tag += '<caption class=\"table_title\"><b>크라우드 펀딩 실시/투자 목록</b> </caption>'\r\n");
      out.write("            tag += '<thead class=\"navy\">'\r\n");
      out.write("            tag += '<tr>'\r\n");
      out.write("            tag += '<th scope=\"col\">No.</th>'\r\n");
      out.write("            tag += '<th scope=\"col\">제목</th>'\r\n");
      out.write("            tag += '<th scope=\"col\">시작일</th>'\r\n");
      out.write("            tag += '<th scope=\"col\">마감일</th>'\r\n");
      out.write("            tag += '</tr>'\r\n");
      out.write("            tag += '</thead>'\r\n");
      out.write("            tag += '<tbody class=\"FundingTbody\">'\r\n");
      out.write("            $.each(res, function(i, fund) {\r\n");
      out.write("                i += 1;\r\n");
      out.write("                tag += '<tr>'\r\n");
      out.write("                tag += '<td scope=\"row\" >' + i + '</th>'\r\n");
      out.write("                tag += '<td name=\"\"><a class=\"mypage-link\" href=\"/cloud/funding/fundingDetail?crowdfundingNum=' + fund.crowdfundingNum + '\">' + fund.fundingTitle + '</a></td>'\r\n");
      out.write("                tag += '<td name=\"fundingStartDate\"><a class=\"mypage-link\" href=\"/cloud/funding/fundingDetail?crowdfundingNum=' + fund.crowdfundingNum + '\">' + fund.fundingStartDate + '</td>'\r\n");
      out.write("                tag += '<td name=\"fundingDueDate\"><a class=\"mypage-link\" href=\"/cloud/funding/fundingDetail?crowdfundingNum=' + fund.crowdfundingNum + '\">' + fund.fundingDueDate + '</td>'\r\n");
      out.write("                tag += '</tr>'\r\n");
      out.write("            })\r\n");
      out.write("            $('#section-bar-funding').html(tag);\r\n");
      out.write("        } \r\n");
      out.write(" \t\r\n");
      out.write("    </script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body class=\"bg-black\">\r\n");
      out.write("\r\n");
      out.write("     <nav class=\"navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light site-navbar-target\" id=\"ftco-navbar\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <a class=\"navbar-brand\" href=\"/cloud/home\">SupporterS</a>\r\n");
      out.write("            <button class=\"navbar-toggler js-fh5co-nav-toggle fh5co-nav-toggle\" type=\"button\" data-toggle=\"collapse\" data-target=\"#ftco-nav\" aria-controls=\"ftco-nav\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("                <span class=\"oi oi-menu\"></span> Menu\r\n");
      out.write("            </button>\r\n");
      out.write("            <div class=\"collapse navbar-collapse\" id=\"ftco-nav\">\r\n");
      out.write("                <ul class=\"navbar-nav nav ml-auto\">\r\n");
      out.write("                    <li class=\"nav-item\"><a href=\"/cloud/home\" class=\"nav-link\"><span>Home</span></a></li>\r\n");
      out.write("                    <li class=\"nav-item\"><a href=\"/cloud/member/goPatent\" class=\"nav-link\"><span>특허 / 검색</span></a></li>\r\n");
      out.write("                    <li class=\"nav-item\"><a href=\"/cloud/board/boardListForm\" class=\"nav-link\"><span>Q & A 게시판</span></a></li>\r\n");
      out.write("                    <li class=\"nav-item\"><a href=\"/cloud/survey/goSurvey_list\" class=\"nav-link\"><span>블라인드 테스트</span></a></li>\r\n");
      out.write("                    <li class=\"nav-item\"><a href=\"/cloud/funding/fundingListForm\" class=\"nav-link\"><span>크라우드 펀딩</span></a></li>\r\n");
      out.write("                    ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    ");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"body\">\r\n");
      out.write("\r\n");
      out.write("        <section>\r\n");
      out.write("            <div class=\"ef-tabs ef-tabs-style-shape\" data-effect=\"fade_slide_from_bottom\">\r\n");
      out.write("                <svg class=\"hidden\">\r\n");
      out.write("                    <defs>\r\n");
      out.write("                        <path id=\"tabshape\" d=\"M80,60C34,53.5,64.417,0,0,0v60H80z\" />\r\n");
      out.write("                    </defs>\r\n");
      out.write("                </svg>\r\n");
      out.write("                <nav>\r\n");
      out.write("                    <ul>\r\n");
      out.write("                        <li><a href=\"#section-shape-qna\" id=\"shape-qna\"> <svg viewBox=\"0 0 80 60\" preserveAspectRatio=\"none\">\r\n");
      out.write("                                    <use xlink:href=\"#tabshape\"></use>\r\n");
      out.write("                                </svg> <span><b>내 게시글 목록</b></span>\r\n");
      out.write("                            </a></li>\r\n");
      out.write("                        \r\n");
      out.write("                        ");
      if (_jspx_meth_c_005fif_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                        <li><a href=\"#section-shape-survey\" id=\"shape-survey\"> <svg viewBox=\"0 0 80 60\" preserveAspectRatio=\"none\">\r\n");
      out.write("                                    <use xlink:href=\"#tabshape\"></use>\r\n");
      out.write("                                </svg> <svg viewBox=\"0 0 80 60\" preserveAspectRatio=\"none\">\r\n");
      out.write("                                    <use xlink:href=\"#tabshape\"></use>\r\n");
      out.write("                                </svg> <span><b>블라인드 테스트 현황</b></span>\r\n");
      out.write("                            </a></li>\r\n");
      out.write("                        <li><a href=\"#section-shape-funding\" id=\"shape-funding\"> <svg viewBox=\"0 0 80 60\" preserveAspectRatio=\"none\">\r\n");
      out.write("                                    <use xlink:href=\"#tabshape\"></use>\r\n");
      out.write("                                </svg> <span><b>크라우드 펀딩 현황</b></span>\r\n");
      out.write("                            </a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </nav>\r\n");
      out.write("                <div class=\"content-wrap\">\r\n");
      out.write("                    <section id=\"section-bar-qna\">\r\n");
      out.write("                        \r\n");
      out.write("                    </section>\r\n");
      out.write("\r\n");
      out.write("                    <section id=\"section-bar-patent\"> \r\n");
      out.write("                    \r\n");
      out.write("                    </section>\r\n");
      out.write("\r\n");
      out.write("                    <section id=\"section-bar-item\"> \r\n");
      out.write("                    \r\n");
      out.write("                    </section>\r\n");
      out.write("\r\n");
      out.write("                    <section id=\"section-bar-survey\">\r\n");
      out.write("                      \r\n");
      out.write("                    </section>\r\n");
      out.write("\r\n");
      out.write("                    <section id=\"section-bar-funding\">\r\n");
      out.write("                        \r\n");
      out.write("                     \r\n");
      out.write("                    </section>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- /content -->\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- /tabs -->\r\n");
      out.write("        </section>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("<script src=\"/cloud/resources/js/jquery-migrate-3.0.1.min.js\"></script>\r\n");
      out.write("<script src=\"/cloud/resources/js/popper.min.js\"></script>\r\n");
      out.write("<script src=\"/cloud/resources/js/bootstrap.min.js\"></script>\r\n");
      out.write("<script src=\"/cloud/resources/js/jquery.easing.1.3.js\"></script>\r\n");
      out.write("<script src=\"/cloud/resources/js/jquery.waypoints.min.js\"></script>\r\n");
      out.write("<script src=\"/cloud/resources/js/jquery.stellar.min.js\"></script>\r\n");
      out.write("<script src=\"/cloud/resources/js/owl.carousel.min.js\"></script>\r\n");
      out.write("<script src=\"/cloud/resources/js/jquery.magnific-popup.min.js\"></script>\r\n");
      out.write("<script src=\"/cloud/resources/js/aos.js\"></script>\r\n");
      out.write("<script src=\"/cloud/resources/js/jquery.animateNumber.min.js\"></script>\r\n");
      out.write("<script src=\"/cloud/resources/js/scrollax.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script src=\"/cloud/resources/js/main.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/member/Mypage.jsp(619,20) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.loginId==null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                        <li style=\"margin-left: 20px;\" class=\"nav-item cta\">\r\n");
          out.write("                            <div class=\"dropdown show\">\r\n");
          out.write("                                <a class=\"btn btn-primary py-3 px-4\" href=\"#\" role=\"button\" id=\"dropdownMenuLink\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
          out.write("                                    <span class=\"member-btn\">로그인/회원가입</span>\r\n");
          out.write("                                </a>\r\n");
          out.write("\r\n");
          out.write("                                <div class=\"dropdown-menu\" aria-labelledby=\"dropdownMenuLink\">\r\n");
          out.write("                                    <a class=\"dropdown-item\" href=\"/cloud/member/gologin\"><span class=\"member-btn\">로그인</span></a>\r\n");
          out.write("                                    <a class=\"dropdown-item\" href=\"/cloud/member/gosign\"><span class=\"member-btn\">회원가입</span></a>\r\n");
          out.write("                                    <a class=\"dropdown-item\" href=\"/cloud/member/gofindid\"><span class=\"member-btn\">아이디/비밀번호 찾기</span></a>\r\n");
          out.write("                                </div>\r\n");
          out.write("                            </div>\r\n");
          out.write("                        </li>\r\n");
          out.write("                    ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /WEB-INF/views/member/Mypage.jsp(635,20) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.loginId!=null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                        <li style=\"margin-left: 20px;\" class=\"nav-item cta\">\r\n");
          out.write("                            <div class=\"dropdown show\">\r\n");
          out.write("                                <a class=\"btn btn-primary py-3 px-4\" href=\"#\" role=\"button\" id=\"dropdownMenuLink\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
          out.write("                                    <span class=\"member-btn\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.loginName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write(' ');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.loginType}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("님</span>\r\n");
          out.write("                                </a>\r\n");
          out.write("\r\n");
          out.write("                                <div class=\"dropdown-menu\" aria-labelledby=\"dropdownMenuLink\">\r\n");
          out.write("                                    <a class=\"dropdown-item\" href=\"/cloud/member/goMypage\">마이페이지</a>\r\n");
          out.write("                                    <a class=\"dropdown-item\" href=\"/cloud/member/goupdate\">회원 정보 수정</a>\r\n");
          out.write("                                    <a class=\"dropdown-item\" href=\"/cloud/member/logout\">로그아웃</a>\r\n");
          out.write("                                </div>\r\n");
          out.write("                            </div>\r\n");
          out.write("                        </li>\r\n");
          out.write("                    ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent(null);
      // /WEB-INF/views/member/Mypage.jsp(671,24) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.loginType == 'inventor'||sessionScope.loginType == 'enp'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                        <li><a id=\"patentList\" href=\"#section-shape-patent\"> <svg viewBox=\"0 0 80 60\" preserveAspectRatio=\"none\">\r\n");
          out.write("                                    <use xlink:href=\"#tabshape\"></use>\r\n");
          out.write("                                </svg> <svg viewBox=\"0 0 80 60\" preserveAspectRatio=\"none\">\r\n");
          out.write("                                    <use xlink:href=\"#tabshape\"></use>\r\n");
          out.write("                                </svg> <span><b>특허 보유/사용 현황</b></span>\r\n");
          out.write("                            </a></li>\r\n");
          out.write("                        <li><a id=\"itemList\" href=\"#section-shape-item\"> <svg viewBox=\"0 0 80 60\" preserveAspectRatio=\"none\">\r\n");
          out.write("                                    <use xlink:href=\"#tabshape\"></use>\r\n");
          out.write("                                </svg> <svg viewBox=\"0 0 80 60\" preserveAspectRatio=\"none\">\r\n");
          out.write("                                    <use xlink:href=\"#tabshape\"></use>\r\n");
          out.write("                                </svg> <span><b>시제품, 출시품 등록 현황</b></span>\r\n");
          out.write("                            </a></li>\r\n");
          out.write("                        ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
    }
    return false;
  }
}
