/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.21
 * Generated at: 2019-10-09 05:27:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1562034500000L));
    _jspx_dependants.put("jar:file:/C:/Users/창민/Documents/GitHub/GoodDeV/ChanMin/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/GoodDeV/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <title>SupporterS :: Main</title>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("\r\n");
      out.write("    <script src=\"/cloud/resources/js/jquery-3.4.1.min.js\"></script>\r\n");
      out.write("    <script src=\"/cloud/resources/js/jquery-ui.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- <link href=\"//netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css\" rel=\"stylesheet\" id=\"bootstrap-css\"> -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/cloud/resources/css/open-iconic-bootstrap.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/cloud/resources/css/animate.css\">\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/cloud/resources/css/owl.carousel.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/cloud/resources/css/owl.theme.default.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/cloud/resources/css/magnific-popup.css\">\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/cloud/resources/css/aos.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/cloud/resources/css/ionicons.min.css\">\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/cloud/resources/css/flaticon.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/cloud/resources/css/icomoon.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/cloud/resources/css/style.css\">\r\n");
      out.write("    <!-- <link rel=\"stylesheet\" href=\"/cloud/resources/css/chat_index.css\"> -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/cloud/resources/css/new-comment.css\">\r\n");
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("    window.onload = function (){\r\n");
      out.write("\t\tinit();\r\n");
      out.write("\t}\r\n");
      out.write("    \r\n");
      out.write("\tfunction init(){\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\t\"url\" :\"/cloud/chat/selectAll\",\r\n");
      out.write("\t\t\t\"method\" : \"get\",\r\n");
      out.write("\t\t\t\"data\":{\r\n");
      out.write("\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\t\"success\":function(result){\r\n");
      out.write("\t\t\t\tvar panelbody = document.getElementById(\"panelbody\");\r\n");
      out.write("\t\t\t\tpanelbody.innerHTML=\" <header class='text-left'>\"\r\n");
      out.write("\t\t\t\t$(result).each(function(index,item){\r\n");
      out.write("\t\t\t\t\tpanelbody.innerHTML\r\n");
      out.write("\t\t\t\t\t\t+=\"<article class='row'><div class='col-md-10 col-sm-10'> <div class='panel panel-default'>\"\r\n");
      out.write("\t\t           \t \t+\"<div class='panel-body' >\"\r\n");
      out.write("\t\t\t\t\t\t+\"<time class='comment-date' datetime=''><i class='fa fa-clock-o'></i> \"+item.regdate+ \"</time>\"\r\n");
      out.write("\t\t\t\t\t\t+\"</header>\"\r\n");
      out.write("\t\t\t\t\t\t+\"<div class='comment-post'> <p>\"+item.memo+\"</p>\t</div></article></div>\"\r\n");
      out.write("\t\t\t\t})\t\t\r\n");
      out.write("\t\t\t\tpanelbody.innerHTML+=\"<div class='search-form'>\"\r\n");
      out.write("\t\t\t\t\t+\"<input type='text' class='searchWord' id='memo' placeholder='메시지를 입력하세요'>\"\r\n");
      out.write("\t\t\t\t\t+\"<button onclick='Regist()'  type='button' style='margin-left:10px; font-size:12px;' class='btn btn-outline-primary btn-rounded waves-effect'>입력하기</button>\"\r\n");
      out.write("\t\t\t   \t\t+\"   </div> </div> </div> \"\r\n");
      out.write("\t\t\t\tconsole.log(result);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\t           \t \t\r\n");
      out.write("\t          \r\n");
      out.write("    \r\n");
      out.write("   $(document).ready(function(){\r\n");
      out.write("\t   var panelbody = document.getElementById(\"panelbody\");\r\n");
      out.write("\t   panelbody.scrollTop = panelbody.scrollHeight;\r\n");
      out.write("\t  $(\"#panelbody\").scrollTop($(\"#panelbody\")[0].scrollHeight) \r\n");
      out.write("   });\r\n");
      out.write("    function Regist() {\r\n");
      out.write("\t\tvar memo = document.getElementById(\"memo\");\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\t\"url\" : \"/cloud/chat/insert\",\r\n");
      out.write("\t\t\t\"method\" : \"post\",\r\n");
      out.write("\t\t\t\"data\" : {\r\n");
      out.write("\t\t\t\t\"memo\" : memo.value\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\t\"success\" : function(result) {\r\n");
      out.write("\t\t\t\tvar panelbody = document.getElementById(\"panelbody\");\r\n");
      out.write("\t\t\t\tinit();\r\n");
      out.write("\t\t\t\tconsole.log(result);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body data-spy=\"scroll\" data-target=\".site-navbar-target\" data-offset=\"300\">\r\n");
      out.write("\r\n");
      out.write("    <nav class=\"navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light site-navbar-target\" id=\"ftco-navbar\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <a class=\"navbar-brand\" href=\"/cloud/home\">SupporterS</a>\r\n");
      out.write("            <button class=\"navbar-toggler js-fh5co-nav-toggle fh5co-nav-toggle\" type=\"button\" data-toggle=\"collapse\" data-target=\"#ftco-nav\" aria-controls=\"ftco-nav\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("                <span class=\"oi oi-menu\"></span> Menu\r\n");
      out.write("            </button>\r\n");
      out.write("            <div class=\"collapse navbar-collapse\" id=\"ftco-nav\">\r\n");
      out.write("                <ul class=\"navbar-nav nav ml-auto\">\r\n");
      out.write("                    <li class=\"nav-item\"><a href=\"/cloud/home\" class=\"nav-link\"><span>Home</span></a></li>\r\n");
      out.write("                    <li class=\"nav-item\"><a href=\"/cloud/member/goPatent\" class=\"nav-link\"><span>특허 / 검색</span></a></li>\r\n");
      out.write("                    <li class=\"nav-item\"><a href=\"/cloud/board/boardListForm\" class=\"nav-link\"><span>Q & A 게시판</span></a></li>\r\n");
      out.write("                    <li class=\"nav-item\"><a href=\"/cloud/survey/goSurvey_list\" class=\"nav-link\"><span>블라인드 테스트</span></a></li>\r\n");
      out.write("                    <li class=\"nav-item\"><a href=\"/cloud/funding/fundingListForm\" class=\"nav-link\"><span>크라우드 펀딩</span></a></li>\r\n");
      out.write("                    ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    ");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("\r\n");
      out.write("    <section class=\"hero-wrap js-fullheight\" style=\"background-image: url('/cloud/resources/images/about_2.jpg');\" data-section=\"home\">\r\n");
      out.write("        <div class=\"overlay\"></div>\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row no-gutters slider-text js-fullheight align-items-center justify-content-end\" data-scrollax-parent=\"true\">\r\n");
      out.write("                <div class=\"col-md-6 ftco-animate\" data-scrollax=\" properties: { translateY: '70%' }\">\r\n");
      out.write("                    <h1 class=\"mb-4\" data-scrollax=\"properties: { translateY: '30%', opacity: 1.6 }\">Of the CEO, <br>By the CEO, <br>For the CEO.</h1>\r\n");
      out.write("                    <p class=\"mb-4\" data-scrollax=\"properties: { translateY: '30%', opacity: 1.6 }\">창업자들을 위한 모든 지원이 여기 있습니다.<br>지금 바로 검색해보세요!</p>\r\n");
      out.write("                    <p><a href=\"/cloud/member/searchGo\" class=\"btn btn-primary py-3 px-4\" style=\"font-size: 1em;\"><span class=\"span_hover\">특허 / 제품 검색하기</span></a>\r\n");
      out.write("                    </p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <section class=\"ftco-section ftco-counter ftco-no-pt ftco-no-pb img\" id=\"section-counter\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row d-md-flex align-items-center justify-content-end\">\r\n");
      out.write("                <div class=\"col-lg-12\">\r\n");
      out.write("                    <div class=\"ftco-counter-wrap\">\r\n");
      out.write("                        <div class=\"row no-gutters d-md-flex align-items-center align-items-stretch\">\r\n");
      out.write("                            <div class=\"col-md-3 d-flex justify-content-center counter-wrap ftco-animate\">\r\n");
      out.write("                                <div class=\"block-18\">\r\n");
      out.write("                                    <div class=\"text\">\r\n");
      out.write("                                        <img src=\"/cloud/resources/images/certifications.png\" alt=\"\" class=\"main_icon\">\r\n");
      out.write("                                        <strong class=\"number\" data-number=\"158\">0</strong>\r\n");
      out.write("                                        <span>실제 창업 성공 건수</span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"col-md-3 d-flex justify-content-center counter-wrap ftco-animate\">\r\n");
      out.write("                                <div class=\"block-18\">\r\n");
      out.write("                                    <div class=\"text\">\r\n");
      out.write("                                        <img src=\"/cloud/resources/images/handshakes.png\" alt=\"\" class=\"main_icon\">\r\n");
      out.write("                                        <strong class=\"number\" data-number=\"1087\">0</strong>\r\n");
      out.write("                                        <span>특허 출원 및 <br>사용 허가 합의 건수</span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"col-md-3 d-flex justify-content-center counter-wrap ftco-animate\">\r\n");
      out.write("                                <div class=\"block-18\">\r\n");
      out.write("                                    <div class=\"text\">\r\n");
      out.write("                                        <img src=\"/cloud/resources/images/ranks.png\" alt=\"\" class=\"main_icon\">\r\n");
      out.write("                                        <strong class=\"number\" data-number=\"564\">0</strong>\r\n");
      out.write("                                        <span>특허 보유 회원 수</span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"col-md-3 d-flex justify-content-center counter-wrap ftco-animate\">\r\n");
      out.write("                                <div class=\"block-18\">\r\n");
      out.write("                                    <div class=\"text\">\r\n");
      out.write("                                        <img src=\"/cloud/resources/images/quality-assurances.png\" alt=\"\" class=\"main_icon\">\r\n");
      out.write("                                        <strong class=\"number\" data-number=\"500\">0</strong>\r\n");
      out.write("                                        <span>실제 출시 된 상품 건수\r\n");
      out.write("                                            <!--&amp;--></span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <section class=\"ftco-section ftco-no-pb ftco-services\" id=\"FAQ-section\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row justify-content-center pb-5\">\r\n");
      out.write("                <div class=\"col-md-10 heading-section text-center ftco-animate\">\r\n");
      out.write("                    <span class=\"subheading\">남녀노소 누구나</span>\r\n");
      out.write("                    <h2 class=\"mb-4\">특허에 대한 A to Z</h2>\r\n");
      out.write("                    <p>초보자도 쉽게 이해할 수 있는 특허 관련 FAQ를 모았습니다.</p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"row no-gutters\">\r\n");
      out.write("                <div class=\"col-md-5 col-lg-3 ftco-animate py-4 nav-link-wrap\">\r\n");
      out.write("                    <div class=\"nav flex-column nav-pills\" id=\"v-pills-tab\" role=\"tablist\" aria-orientation=\"vertical\">\r\n");
      out.write("                        <a class=\"nav-link px-4 py-1 active\" id=\"v-pills-1-tab\" data-toggle=\"pill\" href=\"#v-pills-1\" role=\"tab\" aria-controls=\"v-pills-1\" aria-selected=\"true\"><span class=\"mr-3 flaticon-ideas\"></span> 특허 검색</a>\r\n");
      out.write("\r\n");
      out.write("                        <a class=\"nav-link px-4 py-1\" id=\"v-pills-2-tab\" data-toggle=\"pill\" href=\"#v-pills-2\" role=\"tab\" aria-controls=\"v-pills-2\" aria-selected=\"false\"><span class=\"mr-3 flaticon-web-design\"></span> 특허의 종류</a>\r\n");
      out.write("\r\n");
      out.write("                        <a class=\"nav-link px-4 py-1\" id=\"v-pills-3-tab\" data-toggle=\"pill\" href=\"#v-pills-3\" role=\"tab\" aria-controls=\"v-pills-3\" aria-selected=\"false\"><span class=\"mr-3 flaticon-flasks\"></span> 특허 등록</a>\r\n");
      out.write("\r\n");
      out.write("                        <a class=\"nav-link px-4 py-1\" id=\"v-pills-4-tab\" data-toggle=\"pill\" href=\"#v-pills-4\" role=\"tab\" aria-controls=\"v-pills-4\" aria-selected=\"false\"><span class=\"mr-3 flaticon-analysis\"></span> 특허 사용 허가</a>\r\n");
      out.write("\r\n");
      out.write("                        <a class=\"nav-link px-4 py-1\" id=\"v-pills-5-tab\" data-toggle=\"pill\" href=\"#v-pills-5\" role=\"tab\" aria-controls=\"v-pills-5\" aria-selected=\"false\"><span class=\"mr-3 flaticon-flasks\"></span> 필요 서류 관련</a>\r\n");
      out.write("\r\n");
      out.write("                        <a class=\"nav-link px-4 py-1\" id=\"v-pills-6-tab\" data-toggle=\"pill\" href=\"#v-pills-6\" role=\"tab\" aria-controls=\"v-pills-6\" aria-selected=\"false\"><span class=\"mr-3 flaticon-ux-design\"></span> 기타 FAQ</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-7 col-lg-9 ftco-animate p-4 p-md-5 d-flex align-items-center\">\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"tab-content pl-lg-4\" id=\"v-pills-tabContent\">\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"tab-pane fade show active py-0 py-lg-5\" id=\"v-pills-1\" role=\"tabpanel\" aria-labelledby=\"v-pills-1-tab\">\r\n");
      out.write("                            <div class=\"d-lg-flex\">\r\n");
      out.write("                                <div class=\"icon-law mr-md-4 mr-lg-5\">\r\n");
      out.write("                                <span class=\"icon mb-3 d-block flaticon-search\"></span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"text\">\r\n");
      out.write("                                    <h2 class=\"mb-4\">특허 검색은 어떻게 하나요?</h2>\r\n");
      out.write("                                    <p>처음 접하는 회원을 위한 초보자 검색, <br>상세한 정보를 찾을 수 있는 일반 검색 기능을 지원합니다.</p>\r\n");
      out.write("                                    <p>초보자 검색은 특허 종류부터 분야, 특정 단어 포함 여부 등을 포함해 간단한 절차로 많은 결과를 포함합니다.\r\n");
      out.write("                                    <br>일반 검색은 특허 설명에 포함되어 있는 문장을 포함해 검색할 수 있으며, 특정 전문 기술이 포함된 특허도 검색하실 수 있습니다.\r\n");
      out.write("                                    </p>\r\n");
      out.write("                                    <p><a href=\"/cloud/member/searchGo\" class=\"btn btn-primary px-4 py-3\" style=\"background-color: #6e5773 !important; border:none !important;\">검색하기&nbsp;<span class=\"ion-ios-arrow-round-forward\"></span></a></p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"tab-pane fade py-0 py-lg-5\" id=\"v-pills-3\" role=\"tabpanel\" aria-labelledby=\"v-pills-3-tab\">\r\n");
      out.write("                            <div class=\"d-lg-flex\">\r\n");
      out.write("                                <div class=\"icon-law mr-md-4 mr-lg-5\">\r\n");
      out.write("                                <span class=\"icon mb-3 d-block flaticon-diploma\"></span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"text\">\r\n");
      out.write("                                    <h2 class=\"mb-4\">특허 등록</h2>\r\n");
      out.write("                                    <p>우선 '출원'신청을 합니다. 이에 대해 특허 등록을 하고자 하는 것에 대한 명세서, 선언서, 제품 설명서 등을 첨부하게 됩니다.</p>\r\n");
      out.write("                                    <p><b>출원후 특허청에서 '등록' 승인이 된 시점부터 특허권은 효력을 발휘합니다.</b>\r\n");
      out.write("                                    <br>출원이 완료됐다 해서 정식으로 특허권을 가지게 된 것은 아닙니다.\r\n");
      out.write("                                    </p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"tab-pane fade py-0 py-lg-5\" id=\"v-pills-4\" role=\"tabpanel\" aria-labelledby=\"v-pills-4-tab\">\r\n");
      out.write("                            <div class=\"d-lg-flex\">\r\n");
      out.write("                                <div class=\"icon-law mr-md-4 mr-lg-5\">\r\n");
      out.write("                                <span class=\"icon mb-3 d-block flaticon-handshake\"></span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"text\">\r\n");
      out.write("                                    <h2 class=\"mb-4\">특허 사용 허가</h2>\r\n");
      out.write("                                    <p><b>우선 운영진은 특허 사용허가 절차 과정에 대해 어떤 관여도 할 수 없음을 밝힙니다.</b></p>\r\n");
      out.write("                                    <p>우선 가계약 형식으로 신청을 진행합니다. 이후 특허 보유자가 긍정적 의사를 표했을 경우 사용허가서를 작성한 후, 사용 계약서와 사용 허가서를 양측에 1장씩 총 2장을 보유하게 되면 정식으로 특허권을 사용할 수 있습니다.</p>\r\n");
      out.write("\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"tab-pane fade py-0 py-lg-5\" id=\"v-pills-2\" role=\"tabpanel\" aria-labelledby=\"v-pills-2-tab\">\r\n");
      out.write("                            <div class=\"d-lg-flex\">\r\n");
      out.write("                                <div class=\"icon-law mr-md-4 mr-lg-5\">\r\n");
      out.write("                                <span class=\"icon mb-3 d-block flaticon-data\"></span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"text\">\r\n");
      out.write("                                    <h2 class=\"mb-4\">특허의 종류</h2>\r\n");
      out.write("                                    <p>특허는 크게 발명에 대한 특허, 실용신안권, 디자인권, 상표권 등으로 나뉩니다.</p>\r\n");
      out.write("                                    <p>특허란 '어떠한 발명에 대하여 개인이나 단체가 독점적인 권리를 만드는 것'을 의미합니다. 특허의 범위는 물질적인 여부를 가리지 않고 '발명'에 대한 모든 것이 포함될 수 있습니다. \r\n");
      out.write("                                    <br>제품에 대한 특허, 방법 및 기술에 대한 특허, 디자인 및 상표에 대한 특허 모두가 포함됩니다.\r\n");
      out.write("                                    </p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"tab-pane fade py-0 py-lg-5\" id=\"v-pills-5\" role=\"tabpanel\" aria-labelledby=\"v-pills-5-tab\">\r\n");
      out.write("                            <div class=\"d-lg-flex\">\r\n");
      out.write("                                <div class=\"icon-law mr-md-4 mr-lg-5\">\r\n");
      out.write("                                <span class=\"icon mb-3 d-block flaticon-contract\"></span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"text\">\r\n");
      out.write("                                    <h2 class=\"mb-4\">필요 서류 관련</h2>\r\n");
      out.write("                                    <p>특허 출원 신청 및 등록 절차에 필요한 서류와<br>특허 사용허가에 대한 서류가 상이하오니 사전 확인은 필수입니다.</p>\r\n");
      out.write("                                    <p>특허 사용허가는 특허 보유자와 사용 신청인 간에 절차가 진행되므로, 관련 서류를 꼼꼼히 확인할 필요가 있습니다.</p>\r\n");
      out.write("                                    <p><a href=\"#\" class=\"btn btn-primary px-4 py-3\" style=\"background-color: #6e5773 !important; border:none !important;\">서식 파일 다운로드&nbsp;<span class=\"ion-ios-arrow-round-forward\"></span></a></p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"tab-pane fade py-0 py-lg-5\" id=\"v-pills-6\" role=\"tabpanel\" aria-labelledby=\"v-pills-6-tab\">\r\n");
      out.write("                            <div class=\"d-lg-flex\">\r\n");
      out.write("                                <div class=\"icon-law mr-md-4 mr-lg-5\">\r\n");
      out.write("                                <span class=\"icon mb-3 d-block flaticon-question\"></span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"text\">\r\n");
      out.write("                                    <h2 class=\"mb-4\">기타 FAQ</h2>\r\n");
      out.write("                                    <p>기타 궁금한 사항이나 특정 분야에 대한 질문은 Q & A 게시판에서 자유롭게 받고 있습니다. <br>운영진 및 회원간의 자유로운 질답도 가능하오니 무엇이든 물어보세요.</p>\r\n");
      out.write("                                    <p><a href=\"/cloud/board/boardListForm\" class=\"btn btn-primary px-4 py-3\" style=\"background-color: #6e5773 !important; border:none !important;\">질문하러 가기&nbsp;<span class=\"ion-ios-arrow-round-forward\"></span></a></p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    \r\n");
      out.write("    <section class=\"ftco-section\" id=\"blog-section\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row justify-content-center mb-5 pb-5\">\r\n");
      out.write("                <div class=\"col-md-10 heading-section text-center ftco-animate\">\r\n");
      out.write("                    <h2 class=\"mb-4\">실시간 채팅</h2>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!--chat start-->\r\n");
      out.write("            <div class=\"row\" style=\"vertical-align: middle; margin: 0 auto; justify-content: center;\">\r\n");
      out.write("                <div class=\"container\" id=\"chat-container\">\r\n");
      out.write("                    <!-- <h2 class=\"page-header\">Comments</h2> -->\r\n");
      out.write("                    <div class=\"comment-lists\" id=\"panelbody\">\r\n");
      out.write("                    \r\n");
      out.write("                      <div class='search-form'>\r\n");
      out.write("\t\t\t\t\t\t<input type='text' class='searchWord' id='memo' placeholder='메시지를 입력하세요'>\r\n");
      out.write("\t\t\t\t\t\t<button onclick='Regist()'  type='button' style='margin-left:10px; font-size:12px;' class='btn btn-outline-primary btn-rounded waves-effect'>입력하기</button>\r\n");
      out.write("\t\t\t\t   \t\t </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <!-- <section class=\"ftco-section\" id=\"chat-section\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row justify-content-center mb-5 pb-5\">\r\n");
      out.write("                <div class=\"col-md-10 heading-section text-center ftco-animate\">\r\n");
      out.write("                    <h2 class=\"mb-3\">실시간 채팅</h2>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            chat start\r\n");
      out.write("            <div class=\"row\" style=\"vertical-align: middle; margin: 0 auto; justify-content: center;\">\r\n");
      out.write("                <div class=\"container\" id=\"chat-container\">\r\n");
      out.write("                    <h2 class=\"page-header\">Comments</h2>\r\n");
      out.write("                    <div class=\"comment-lists\">\r\n");
      out.write("\r\n");
      out.write("                        other Comment\r\n");
      out.write("                        <article class=\"row\">\r\n");
      out.write("                            <div class=\"col-md-10 col-sm-10\">\r\n");
      out.write("                                <div class=\"panel panel-default\">\r\n");
      out.write("                                    <div class=\"panel-body\">\r\n");
      out.write("                                        <header class=\"text-left\">\r\n");
      out.write("                                            Index는 익명 채팅이니까 memberId 나올 필요 없음\r\n");
      out.write("                                            <div class=\"comment-user\"><i class=\"fa fa-user\"></i> [memberId]</div>\r\n");
      out.write("                                            <time class=\"comment-date\" datetime=\"\"><i class=\"fa fa-clock-o\"></i> 2019-10-02 | 14:29</time>\r\n");
      out.write("\r\n");
      out.write("                                        </header>\r\n");
      out.write("                                        <div class=\"comment-post\">\r\n");
      out.write("                                            <p>\r\n");
      out.write("                                                [다른 사람들이 입력한 내용은 여기서 나오게끔]\r\n");
      out.write("                                            </p>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </article>\r\n");
      out.write("\r\n");
      out.write("                        my Comment\r\n");
      out.write("                        <article class=\"row\">\r\n");
      out.write("                            <div class=\"col-md-10 col-sm-10\">\r\n");
      out.write("                                <div class=\"panel panel-default\">\r\n");
      out.write("                                    <div class=\"panel-body\">\r\n");
      out.write("                                        <header class=\"text-right\">\r\n");
      out.write("                                            <div class=\"comment-user\"><i class=\"fa fa-user\"></i> [내 댓글]</div>\r\n");
      out.write("                                            <time class=\"comment-date\" datetime=\"\"><i class=\"fa fa-clock-o\"></i> 2019-10-02 | 14:29</time>\r\n");
      out.write("                                        </header>\r\n");
      out.write("                                        <div class=\"comment-post\">\r\n");
      out.write("                                            <p class=\"my-comment\">\r\n");
      out.write("                                                [내가 입력한건 이렇게 나오게끔]\r\n");
      out.write("                                            </p>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </article>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"search-form\">\r\n");
      out.write("                        <input type=\"text\" class=\"searchWord\" placeholder=\" 메시지를 입력하세요\">\r\n");
      out.write("                        <button type=\"button\" style=\"margin-left:10px; font-size:12px;\" class=\"btn btn-outline-primary btn-rounded waves-effect\">입력하기</button>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    </section> -->\r\n");
      out.write("\r\n");
      out.write("    <section class=\"ftco-section contact-section ftco-no-pb bg-light\" id=\"contact-section\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row justify-content-center mb-5 pb-3\">\r\n");
      out.write("                <div class=\"col-md-10 heading-section text-center ftco-animate\">\r\n");
      out.write("                    <span class=\"subheading\">본사 주소 및 연락처</span>\r\n");
      out.write("                    <h2 class=\"mb-4\">공식 연락처</h2>\r\n");
      out.write("                    <p>특허 출원 및 사용 허가 관련 최종 절차는 모두 본사에서 진행됩니다.</p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"row d-flex contact-info mb-5\">\r\n");
      out.write("                <div class=\"col-md-6 col-lg-3 d-flex ftco-animate\">\r\n");
      out.write("                    <div class=\"align-self-stretch box p-4 text-center\">\r\n");
      out.write("                        <div class=\"icon d-flex align-items-center justify-content-center\">\r\n");
      out.write("                            <span class=\"icon-map-signs\"></span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <h3 class=\"mb-4\">찾아오는 길</h3>\r\n");
      out.write("                        <p>4th floor, 513, Yeongdong-daero, Gangnam-gu, Seoul, Republic of Korea</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-6 col-lg-3 d-flex ftco-animate\">\r\n");
      out.write("                    <div class=\"align-self-stretch box p-4 text-center\">\r\n");
      out.write("                        <div class=\"icon d-flex align-items-center justify-content-center\">\r\n");
      out.write("                            <span class=\"icon-phone2\"></span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <h3 class=\"mb-4\">대표 전화번호</h3>\r\n");
      out.write("                        <p><a href=\"tel://1234567920\">+82 02 6000 0114</a></p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-6 col-lg-3 d-flex ftco-animate\">\r\n");
      out.write("                    <div class=\"align-self-stretch box p-4 text-center\">\r\n");
      out.write("                        <div class=\"icon d-flex align-items-center justify-content-center\">\r\n");
      out.write("                            <span class=\"icon-paper-plane\"></span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <h3 class=\"mb-4\">대표 이메일</h3>\r\n");
      out.write("                        <p><a href=\"mailto:info@yoursite.com\">info@yoursite.com</a></p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-6 col-lg-3 d-flex ftco-animate\">\r\n");
      out.write("                    <div class=\"align-self-stretch box p-4 text-center\">\r\n");
      out.write("                        <div class=\"icon d-flex align-items-center justify-content-center\">\r\n");
      out.write("                            <span class=\"icon-globe\"></span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <h3 class=\"mb-4\">공식 사이트</h3>\r\n");
      out.write("                        <p><a href=\"#\">index.com</a></p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <footer class=\"ftco-footer ftco-section\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row mb-5\">\r\n");
      out.write("                <div class=\"col-md\">\r\n");
      out.write("                    <div class=\"ftco-footer-widget mb-4\">\r\n");
      out.write("                        <h2 class=\"ftco-heading-2\">About <span>SupporterS</span></h2>\r\n");
      out.write("                        <p>창업자가 궁금해하는 것, <br>필요로 하는 것, <br>필요로 할 것들을 최대한 지원하기 위해 만든 사이트입니다.</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md\">\r\n");
      out.write("                    <div class=\"ftco-footer-widget mb-4 ml-md-4\">\r\n");
      out.write("                        <h2 class=\"ftco-heading-2\">바로가기</h2>\r\n");
      out.write("                        <ul class=\"list-unstyled\">\r\n");
      out.write("                            <li><a href=\"/cloud/home\"><span class=\"icon-long-arrow-right mr-2\"></span>Home</a></li>\r\n");
      out.write("                            <li><a href=\"/cloud/member/goPatent\"><span class=\"icon-long-arrow-right mr-2\"></span>검색 및 특허 관련</a></li>\r\n");
      out.write("                            <li><a href=\"/cloud/board/boardListForm\"><span class=\"icon-long-arrow-right mr-2\"></span>Q & A 게시판</a></li>\r\n");
      out.write("                            <li><a href=\"/cloud/survey/surveyListForm\"><span class=\"icon-long-arrow-right mr-2\"></span>블라인드 테스트</a></li>\r\n");
      out.write("                            <li><a href=\"/cloud/funding/fundingListForm\"><span class=\"icon-long-arrow-right mr-2\"></span>크라우드 펀딩</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md\">\r\n");
      out.write("                    <div class=\"ftco-footer-widget mb-4\">\r\n");
      out.write("                        <h2 class=\"ftco-heading-2\">검색 및 특허 관련</h2>\r\n");
      out.write("                        <ul class=\"list-unstyled\">\r\n");
      out.write("                            <li><a href=\"/cloud/member/searchGo\"><span class=\"icon-long-arrow-right mr-2\"> 특허 검색</span></a></li>\r\n");
      out.write("                            <li><a href=\"/cloud/item/searchItem\"><span class=\"icon-long-arrow-right mr-2\"> 제품 검색</span></a></li>\r\n");
      out.write("                            <li><a href=\"/cloud/member/goPatent\"><span class=\"icon-long-arrow-right mr-2\"> 특허 출원 신청</span></a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md\">\r\n");
      out.write("                    <div class=\"ftco-footer-widget mb-4\">\r\n");
      out.write("                        <h2 class=\"ftco-heading-2\">찾아오는 길</h2>\r\n");
      out.write("                        <div class=\"block-23 mb-0\">\r\n");
      out.write("                            <ul>\r\n");
      out.write("                                <li><span class=\"icon icon-map-marker\"></span><span class=\"text\">4th floor, 513, Yeongdong-daero, Gangnam-gu, Seoul, Republic of Korea</span></li>\r\n");
      out.write("                                <li><a href=\"#\"><span class=\"icon icon-phone\"></span><span class=\"text\">+82 02 6000 0114</span></a></li>\r\n");
      out.write("                                <li><a href=\"#\"><span class=\"icon icon-envelope\"></span><span class=\"text\">info@yourdomain.com</span></a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </footer>\r\n");
      out.write("\r\n");
      out.write("    <!-- loader -->\r\n");
      out.write("    <div id=\"ftco-loader\" class=\"show fullscreen\"><svg class=\"circular\" width=\"48px\" height=\"48px\">\r\n");
      out.write("            <circle class=\"path-bg\" cx=\"24\" cy=\"24\" r=\"22\" fill=\"none\" stroke-width=\"4\" stroke=\"#eeeeee\" />\r\n");
      out.write("            <circle class=\"path\" cx=\"24\" cy=\"24\" r=\"22\" fill=\"none\" stroke-width=\"4\" stroke-miterlimit=\"10\" stroke=\"#6082cc\" /></svg></div>\r\n");
      out.write("\r\n");
      out.write("    <script src=\"/cloud/resources/js/jquery.min.js\"></script>\r\n");
      out.write("    <script src=\"/cloud/resources/js/jquery-migrate-3.0.1.min.js\"></script>\r\n");
      out.write("    <script src=\"/cloud/resources/js/popper.min.js\"></script>\r\n");
      out.write("    <script src=\"/cloud/resources/js/bootstrap.min.js\"></script>\r\n");
      out.write("    <script src=\"/cloud/resources/js/jquery.easing.1.3.js\"></script>\r\n");
      out.write("    <script src=\"/cloud/resources/js/jquery.waypoints.min.js\"></script>\r\n");
      out.write("    <script src=\"/cloud/resources/js/jquery.stellar.min.js\"></script>\r\n");
      out.write("    <script src=\"/cloud/resources/js/owl.carousel.min.js\"></script>\r\n");
      out.write("    <script src=\"/cloud/resources/js/jquery.magnific-popup.min.js\"></script>\r\n");
      out.write("    <script src=\"/cloud/resources/js/aos.js\"></script>\r\n");
      out.write("    <script src=\"/cloud/resources/js/jquery.animateNumber.min.js\"></script>\r\n");
      out.write("    <script src=\"/cloud/resources/js/scrollax.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <script src=\"/cloud/resources/js/main.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- <script src=\"/cloud/resources/js/bootstrap.min.js\"></script> -->\r\n");
      out.write("    <!-- <script src=\"//netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js\"></script> -->\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/index.jsp(106,20) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.loginId==null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                        <li style=\"margin-left: 20px;\" class=\"nav-item cta\">\r\n");
          out.write("                            <div class=\"dropdown show\">\r\n");
          out.write("                                <a class=\"btn btn-primary py-3 px-4\" href=\"#\" role=\"button\" id=\"dropdownMenuLink\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
          out.write("                                    <span class=\"member-btn\">로그인/회원가입</span>\r\n");
          out.write("                                </a>\r\n");
          out.write("\r\n");
          out.write("                                <div class=\"dropdown-menu\" aria-labelledby=\"dropdownMenuLink\">\r\n");
          out.write("                                    <a class=\"dropdown-item\" href=\"/cloud/member/gologin\"><span class=\"member-btn\">로그인</span></a>\r\n");
          out.write("                                    <a class=\"dropdown-item\" href=\"/cloud/member/gosign\"><span class=\"member-btn\">회원가입</span></a>\r\n");
          out.write("                                    <a class=\"dropdown-item\" href=\"/cloud/member/gofindid\"><span class=\"member-btn\">아이디/비밀번호 찾기</span></a>\r\n");
          out.write("                                </div>\r\n");
          out.write("                            </div>\r\n");
          out.write("                        </li>\r\n");
          out.write("                    ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /WEB-INF/views/index.jsp(122,20) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.loginId!=null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                        <li style=\"margin-left: 20px;\" class=\"nav-item cta\">\r\n");
          out.write("                            <div class=\"dropdown show\">\r\n");
          out.write("                                <a class=\"btn btn-primary py-3 px-4\" href=\"#\" role=\"button\" id=\"dropdownMenuLink\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
          out.write("                                    <span class=\"member-btn\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.loginName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write(' ');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.loginType}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("님</span>\r\n");
          out.write("                                </a>\r\n");
          out.write("\r\n");
          out.write("                                <div class=\"dropdown-menu\" aria-labelledby=\"dropdownMenuLink\">\r\n");
          out.write("                                    <a class=\"dropdown-item\" href=\"/cloud/member/goMypage\">마이페이지</a>\r\n");
          out.write("                                    <a class=\"dropdown-item\" href=\"/cloud/member/goupdate\">회원 정보 수정</a>\r\n");
          out.write("                                    <a class=\"dropdown-item\" href=\"/cloud/member/logout\">로그아웃</a>\r\n");
          out.write("                                </div>\r\n");
          out.write("                            </div>\r\n");
          out.write("                        </li>\r\n");
          out.write("                    ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }
}
