/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.21
 * Generated at: 2019-10-09 15:07:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.search;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class search_005fpatent_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1562034500000L));
    _jspx_dependants.put("jar:file:/C:/Users/창민/Documents/GitHub/GoodDeV/ChanMin/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/GoodDeV/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("  <head>\r\n");
      out.write("    <title>SupporterS :: Search Patent</title>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("    \r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/cloud/resources/css/open-iconic-bootstrap.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/cloud/resources/css/animate.css\">\r\n");
      out.write("    \r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/cloud/resources/css/owl.carousel.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/cloud/resources/css/owl.theme.default.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/cloud/resources/css/magnific-popup.css\">\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/cloud/resources/css/aos.css\">\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/cloud/resources/css/ionicons.min.css\">\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/cloud/resources/css/flaticon.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/cloud/resources/css/icomoon.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/cloud/resources/css/style.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/cloud/resources/css/search.css\">\r\n");
      out.write("    \r\n");
      out.write("     <style>\r\n");
      out.write("    div.tri-btn{\r\n");
      out.write("    vertical-align: middle;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    margin: 0 auto;\r\n");
      out.write("    justify-content : center;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .btn-primary{\r\n");
      out.write("    margin-left :10px;\r\n");
      out.write("    margin-right:10px;\r\n");
      out.write("    }\r\n");
      out.write("    </style>\r\n");
      out.write("    \r\n");
      out.write("    <script src=\"/cloud/resources/js/jquery-3.4.1.min.js\"></script>\r\n");
      out.write("\t<script src=\"/cloud/resources/js/jquery-ui.min.js\"></script>\r\n");
      out.write("   \r\n");
      out.write("    <script>\r\n");
      out.write("\tvar pageSu;\r\n");
      out.write("\t\r\n");
      out.write("    $(function(){\r\n");
      out.write(" \t\t   pageSu = 9;\r\n");
      out.write(" \t\t   patentTable(pageSu);   \r\n");
      out.write(" \t\t\t\r\n");
      out.write(" \t\t    \r\n");
      out.write(" \t\t\r\n");
      out.write(" \t\t   \r\n");
      out.write(" \t    \t$('#patentBtn').on('click',function(){\r\n");
      out.write(" \t    \t\tvar type = $('#patentType').val();\r\n");
      out.write(" \t    \t\tif(type =='none'){\r\n");
      out.write(" \t    \t\t\talert('산업분야를 클릭하세요!');\r\n");
      out.write(" \t    \t\t\treturn false;\r\n");
      out.write(" \t    \t\t}else{\r\n");
      out.write(" \t    \t\t\tpatentTable(pageSu); \r\n");
      out.write(" \t    \t\t}\r\n");
      out.write(" \t    \t})\r\n");
      out.write(" \t    \t\r\n");
      out.write(" \t    \t\r\n");
      out.write(" \t    \t$('#permitBtn').on('click',function(){\r\n");
      out.write(" \t    \t\tvar memberId = $('#memId').val();\r\n");
      out.write(" \t    \t\tvar patentNum =$('#patentNum').val();\r\n");
      out.write(" \t    \t\tvar itemNum = $('#item-option').val();\r\n");
      out.write(" \t    \t\tvar upload = $('#upload').val();\r\n");
      out.write(" \t    \t\tvar upload1 = $('#upload1').val();\r\n");
      out.write(" \t    \t\tvar formData = new FormData($('#permitForm')[0]);\r\n");
      out.write(" \t    \t\tvar total ={\r\n");
      out.write(" \t    \t\t\t\"memberId\"\t: memberId,\r\n");
      out.write(" \t    \t\t\t\"patentNum\"\t: patentNum,\r\n");
      out.write(" \t    \t\t\t\"itemNum\"\t: itemNum,\r\n");
      out.write(" \t    \t\t\t\"upload\"\t: upload,\r\n");
      out.write(" \t    \t\t\t\"upload1\"\t: upload1\r\n");
      out.write(" \t    \t\t}\r\n");
      out.write(" \t    \t\tif(upload==''||upload.length==0&&upload1==''||upload1.length==0){\r\n");
      out.write(" \t    \t\t\talert('파일을 반드시 첨부하세요!')\r\n");
      out.write(" \t    \t\t\treturn false;\r\n");
      out.write(" \t    \t\t}\r\n");
      out.write(" \t    \t\r\n");
      out.write(" \t    \t\t $.ajax({\r\n");
      out.write(" \t    \t\t\turl : 'permitForm',\r\n");
      out.write(" \t    \t\t\ttype : 'post',\r\n");
      out.write(" \t    \t\t\tenctype : 'multipart/form-data',\r\n");
      out.write(" \t    \t\t\tprocessData : false,\r\n");
      out.write(" \t    \t\t\tcontentType : false,\r\n");
      out.write(" \t    \t\t\tdata : formData,\r\n");
      out.write(" \t    \t\t\tsuccess : function(res){\r\n");
      out.write(" \t    \t\t\t\tif(res=='success'){\r\n");
      out.write(" \t    \t\t\t\t\talert('성공');\r\n");
      out.write(" \t    \t\t\t\t\t$('#exampleModal').modal('hide');\r\n");
      out.write(" \t    \t\t\t\t}else{\r\n");
      out.write(" \t    \t\t\t\t\talert('이미 사용중인 특허번호입니다.');\r\n");
      out.write(" \t    \t\t\t\t}\r\n");
      out.write(" \t    \t\t\t}\r\n");
      out.write(" \t    \t\t})\t \r\n");
      out.write(" \t    \t})\r\n");
      out.write(" \t\t   \r\n");
      out.write("    });\r\n");
      out.write("    \r\n");
      out.write("    function selectIt(){\r\n");
      out.write("    \tvar memberId = $('#memId').val();\r\n");
      out.write("    \t$.ajax({\r\n");
      out.write("    \t\turl : 'memberItemNum',\r\n");
      out.write("    \t\ttype : 'get',\r\n");
      out.write("    \t\tdata :\t{\r\n");
      out.write("    \t\t\tmemberId : memberId\r\n");
      out.write("    \t\t},\r\n");
      out.write("    \t\tsuccess : function(res){\r\n");
      out.write("    \t\t\tvar tag =\"\";\r\n");
      out.write("    \t\t\t$.each(res,function(i,item){\r\n");
      out.write("    \t\t\t\tvar type = item.itemType\r\n");
      out.write("    \t\t\t\tif(type!='none'){\r\n");
      out.write("    \t\t\t\ttag += '<option value=\"'+item.itemNum+'\">'+item.itemName+'</option>'\r\n");
      out.write("    \t\t\t\t}\r\n");
      out.write("    \t\t\t\t})\r\n");
      out.write("    \t\t\t$('#item-option').html(tag);\r\n");
      out.write("    \t\t}\r\n");
      out.write("    \t})\r\n");
      out.write("    \t\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    function checking(){\t\r\n");
      out.write("    \tvar patentNum = $(this).attr('data-value');\r\n");
      out.write("    \t\r\n");
      out.write("    \t$.ajax({\r\n");
      out.write("\t \t\t\turl  : 'selectPatent',\r\n");
      out.write("\t \t\t\ttype : 'get',\r\n");
      out.write("\t \t\t\tdata : {\r\n");
      out.write("\t \t\t\t\tpatentNum : patentNum\r\n");
      out.write("\t \t\t\t},\r\n");
      out.write("\t \t\t\tsuccess : function(res){\r\n");
      out.write("\t \t\t\t\tif(res!=null){\r\n");
      out.write("\t \t\t\t\t\t$(\"#patentNum\").val(res);\t\r\n");
      out.write("\t \t\t\t\t}else{\r\n");
      out.write("\t \t\t\t\t\talert('에러!!');\r\n");
      out.write("\t \t\t\t\t}\r\n");
      out.write("\t \t\t\t\t\r\n");
      out.write("\t \t\t\t}\r\n");
      out.write("\t   \t})  \r\n");
      out.write("\t\t\r\n");
      out.write("    \r\n");
      out.write("    }   \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    jQuery(document).on('click', '#rightBtn', function(){\r\n");
      out.write(" \t   \t\t\tpageSu += 10;\r\n");
      out.write(" \t   \t\t\t$.ajax({\r\n");
      out.write(" \t   \t\t\t\turl: 'patentSu',\r\n");
      out.write(" \t   \t\t\t\ttype : 'get',\r\n");
      out.write(" \t   \t\t\t\tsuccess : function(res){\r\n");
      out.write(" \t   \t\t\t\t\tif(pageSu<res){\r\n");
      out.write(" \t   \t\t\t\t\t\tpatentTable(pageSu); \r\n");
      out.write(" \t   \t\t\t\t\t}else {\t\r\n");
      out.write(" \t   \t\t\t\t\t\tpageSu = 9;\r\n");
      out.write(" \t   \t\t\t\t\t\tpatentTable(pageSu);\r\n");
      out.write(" \t   \t\t\t\t\t\t//ex) 172개 일때, 170개는 보여지지만 2개는 아직 안보임;;\r\n");
      out.write(" \t   \t\t\t\t\t}\r\n");
      out.write(" \t   \t\t\t\t}\r\n");
      out.write(" \t   \t\t\t})\r\n");
      out.write(" \t   }); \r\n");
      out.write("    \r\n");
      out.write("    jQuery(document).on('click', '#leftBtn', function(){\r\n");
      out.write(" \t \t  \t\t\r\n");
      out.write(" \t   \t\t\tpageSu -= 10;\r\n");
      out.write(" \t \t\r\n");
      out.write(" \t \t  \t\tif(pageSu>0){\r\n");
      out.write(" \t \t  \t\t\tpatentTable(pageSu); \r\n");
      out.write(" \t \t  \t\t}else{\r\n");
      out.write(" \t \t  \t\t\tpageSu = 9;\r\n");
      out.write(" \t \t  \t\t\talert('응 첫페이지..');\r\n");
      out.write(" \t \t  \t\t\tpatentTable(pageSu); \r\n");
      out.write(" \t \t  \t\t}\r\n");
      out.write(" \t \t  \t\t\r\n");
      out.write(" });\r\n");
      out.write("    \r\n");
      out.write("   \r\n");
      out.write("    function patentTable(pageSu){\r\n");
      out.write(" \t    var searchWord =$('#searchWord').val()\t\r\n");
      out.write(" \t   \tvar searchItem =$('#searchItem').val()\r\n");
      out.write(" \t   \tvar patentType  =$('#patentType').val()\r\n");
      out.write(" \t   \r\n");
      out.write(" \t   $.ajax({\r\n");
      out.write(" \t   \t\turl : 'patentTable',\r\n");
      out.write(" \t   \t\ttype : 'get',\r\n");
      out.write(" \t   \t\tdata : {\r\n");
      out.write(" \t   \t\t\t pageSu : pageSu\r\n");
      out.write(" \t   \t\t\t,searchWord : searchWord\r\n");
      out.write(" \t   \t\t\t,searchItem : searchItem\r\n");
      out.write(" \t   \t\t\t,patentType : patentType\r\n");
      out.write(" \t   \t\t},\r\n");
      out.write(" \t   \t\tsuccess : output\t   \t\t\r\n");
      out.write(" \t   \t})\r\n");
      out.write(" \t   \r\n");
      out.write(" \t   \r\n");
      out.write("    }\r\n");
      out.write("    function output(res){\r\n");
      out.write(" \t   \tvar tag = '';\r\n");
      out.write("        tag += '<table class=\"pTable\" style=\"width:100%;\">'\r\n");
      out.write("        tag += '<caption class=\"table_title\"><b>검색하신 특허결과입니다.</b></caption>'\r\n");
      out.write("        tag += '<thead class=\"navy\">' \r\n");
      out.write("        tag += '<tr>'   \r\n");
      out.write("        tag += '<th scope=\"col\">No.</th>'        \r\n");
      out.write("        tag += '<th scope=\"col\">분류</th>'       \r\n");
      out.write("        tag += '<th scope=\"col\">특허명</th>'        \r\n");
      out.write("        tag += '<th scope=\"col\">특허<br>보유자</th>'    \r\n");
      out.write("   \t    tag += '<th scope=\"col\">등록날짜</th>'\r\n");
      out.write("   \t    tag += '<th scope=\"col\">특허 <br>사용 신청</th>'\r\n");
      out.write("   \t    tag += '</tr>'\r\n");
      out.write("    \t   tag += '</thead>' \r\n");
      out.write("    \t   tag += '<tbody>'  \r\n");
      out.write("    \t\t   \r\n");
      out.write("    \t\t   \r\n");
      out.write("\r\n");
      out.write("    \t\t   $.each(res, function(i, item) {\r\n");
      out.write("                   tag += '<tr>'\r\n");
      out.write("                   var patentNum = item.patentNum;\r\n");
      out.write("                   var patenttype = item.patenttype;\r\n");
      out.write("                   var patentName = item.patentName;\r\n");
      out.write("                   var patentContent = item.patentContent;\r\n");
      out.write("                   var patentHolderName = item.patentHolderName;\r\n");
      out.write("\r\n");
      out.write("                   if (patentNum.length >= 10) {\r\n");
      out.write("                       //patentNum = patentNum.split(\"-\",2)+\"...\";\r\n");
      out.write("                       patentNum = patentNum.substr(0, 10) + \"...\";\r\n");
      out.write("                       tag += '<th scope=\"row\" name=\"특허번호\">' + patentNum + '</th>'\r\n");
      out.write("                   }  else {\r\n");
      out.write("                       tag += '<th scope=\"row\" name=\"특허번호\">' + patentNum + '</th>'\r\n");
      out.write("                   }\r\n");
      out.write("                   \r\n");
      out.write("                   if (patenttype == null) {\r\n");
      out.write("                       //patenttype = patenttype.substr(0,7)+\"...\";\r\n");
      out.write("                       tag += '<td name=\"분류\" >' + '' + '</td>'\r\n");
      out.write("                   } else if(patenttype.length >= 8 ){\r\n");
      out.write("                      tag += '<td name=\"분류\" >' + patenttype + '</td>'\r\n");
      out.write("                   }\r\n");
      out.write("                   \r\n");
      out.write("                   if (patentName==null) {\r\n");
      out.write("                      tag += '<td name=\"특허명\"><b>' + '' + '</b></td>'\r\n");
      out.write("                   } else if(patentName.length >= 15){\r\n");
      out.write("                       patentName = patentName.substr(0, 24) + \"...\";\r\n");
      out.write("                        tag += '<td name=\"특허명\"><b>' + patentName.split(\"(\", 1) + '</b></td>'\r\n");
      out.write("                   }else{\r\n");
      out.write("                      tag += '<td name=\"특허명\"><b>' + patentName + '</b></td>'\r\n");
      out.write("                   }\r\n");
      out.write("                   /* if(patentContent.length >= 20){\r\n");
      out.write("                      patentContent = patentContent.substr(0,40)+\"...\";\r\n");
      out.write("                       tag += '<td name=\"특허설명\" ><b>'+patentContent+'</b></td>'\r\n");
      out.write("                   } */\r\n");
      out.write("                   if (patentHolderName.length >= 5) {\r\n");
      out.write("                       patentHolderName = patentHolderName.substr(0, 4) + \"...\";\r\n");
      out.write("                       tag += '<td name=\"특허 보유자\" >' + patentHolderName + '</td>'\r\n");
      out.write("                   } else {\r\n");
      out.write("                      tag += '<td name=\"특허 보유자\" >' + patentHolderName + '</td>'\r\n");
      out.write("                   }\r\n");
      out.write("                  /*  else {\r\n");
      out.write("                       tag += '<tr>'\r\n");
      out.write("                       tag += '<th scope=\"row\" name=\"특허번호\">' + patentNum + '</th>'\r\n");
      out.write("                       tag += '<td name=\"분류\" >' + patenttype + '</td>'\r\n");
      out.write("                       tag += '<td name=\"특허명\" ><b>' + patentName + '</b></td>'\r\n");
      out.write("                       /* tag += '<td name=\"특허설명\" ><b>'+patentContent+'</b></td>' \r\n");
      out.write("                       tag += '<td name=\"특허 보유자\" >' + patentHolderName + '</td>'\r\n");
      out.write("                   } */\r\n");
      out.write("\r\n");
      out.write("                   if (item.patentRegDate != null) {\r\n");
      out.write("                       tag += '<td name=\"등록날짜\">' + item.patentRegDate + '</td>'\r\n");
      out.write("                   } else {\r\n");
      out.write("                       tag += '<td >[등록진행중]</td>'\r\n");
      out.write("                   }\r\n");
      out.write("\t\t\t\t   \r\n");
      out.write("                   tag += '<td name=\"서식파일보기\" ><button type=\"button\" class=\"pri\" data-value=\"' + item.patentNum + '\" data-toggle=\"modal\" data-target=\"#exampleModal\">신청하기</button></td>'\r\n");
      out.write("                   \r\n");
      out.write("                   //인터셉터 처리\r\n");
      out.write("                   tag += '</tr>'\r\n");
      out.write("               })\r\n");
      out.write("    \t    \t   \r\n");
      out.write("    \t    \t    tag += '</tbody>'\r\n");
      out.write("    \t    \t    tag += '</table>' \r\n");
      out.write("    \t    \t    tag += '<br><br>'\r\n");
      out.write("    \t    \t\ttag += '<div class=\"tri-btn\">'\r\n");
      out.write("    \t    \t\ttag += '<button id=\"leftBtn\" class=\"btn btn-primary\">◀</button>'\t\r\n");
      out.write("    \t    \t    tag += '<button id=\"rightBtn\" class=\"btn btn-primary\">▶</button>'\t\r\n");
      out.write("    \t    \t    tag +=\t'</div>'\r\n");
      out.write("    \t        $('#section-bar-patent').html(tag);\t\r\n");
      out.write("    \t    \t$('.pri').on('click',checking);    \r\n");
      out.write("    \t    \t$('.pri').on('click',selectIt);\r\n");
      out.write("    \t    }\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    function loginGo(){\r\n");
      out.write("    \twindow.location.href=\"/cloud/member/gologin\";\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    function signGo(){\r\n");
      out.write("    \twindow.location.href=\"/cloud/member/gosign\";\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    function searchGO(){\r\n");
      out.write("    \twindow.location.href=\"/cloud/search/searchGo\";\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    </script>\r\n");
      out.write("  </head>\r\n");
      out.write("<body data-spy=\"scroll\" data-target=\".site-navbar-target\" data-offset=\"300\">\r\n");
      out.write("\t\r\n");
      out.write("   <nav class=\"navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light site-navbar-target\" id=\"ftco-navbar\">\r\n");
      out.write("\t    <div class=\"container\">\r\n");
      out.write("\t      <a class=\"navbar-brand\" href=\"/cloud/home\">SupporterS</a>\r\n");
      out.write("\t      <button class=\"navbar-toggler js-fh5co-nav-toggle fh5co-nav-toggle\" type=\"button\" data-toggle=\"collapse\" data-target=\"#ftco-nav\" aria-controls=\"ftco-nav\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("\t        <span class=\"oi oi-menu\"></span> Menu\r\n");
      out.write("\t      </button>\r\n");
      out.write("\t      <div class=\"collapse navbar-collapse\" id=\"ftco-nav\">\r\n");
      out.write("\t        <ul class=\"navbar-nav nav ml-auto\">\r\n");
      out.write("\t          <li class=\"nav-item\"><a href=\"/cloud/home\" class=\"nav-link\"><span>Home</span></a></li>\r\n");
      out.write("                    <li class=\"nav-item\"><a href=\"/cloud/member/goPatent\" class=\"nav-link\"><span>특허 / 검색</span></a></li>\r\n");
      out.write("                    <li class=\"nav-item\"><a href=\"/cloud/board/boardListForm\" class=\"nav-link\"><span>Q & A 게시판</span></a></li>\r\n");
      out.write("                    <li class=\"nav-item\"><a href=\"/cloud/survey/goSurvey_list\" class=\"nav-link\"><span>블라인드 테스트</span></a></li>\r\n");
      out.write("                    <li class=\"nav-item\"><a href=\"/cloud/funding/fundingListForm\" class=\"nav-link\"><span>크라우드 펀딩</span></a></li>\r\n");
      out.write("\t  \t\t\t ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t </ul>\r\n");
      out.write("\t      </div>\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t  </nav>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t  <section class=\"hero-wrap hero-wrap-2\" style=\"background-image: url('/cloud/resources/images/about_10-1.jpg');\" data-stellar-background-ratio=\"0.5\">\r\n");
      out.write("      <div class=\"overlay\"></div>\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <div class=\"row no-gutters slider-text align-items-end justify-content-center\">\r\n");
      out.write("          <div class=\"col-md-9 ftco-animate pb-5 text-center\">\r\n");
      out.write("            <h1 class=\"mb-3 bread\">Search Patent</h1>\r\n");
      out.write("            <p class=\"breadcrumbs\"><span class=\"mr-2\"><a href=\"home\">Home <i class=\"ion-ios-arrow-forward\"></i></a></span> <span class=\"mr-2\"><a href=\"#\">검색 분류 <i class=\"ion-ios-arrow-forward\"></i></a></span> <span>특허 검색 <i class=\"ion-ios-arrow-forward\"></i></span></p>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("<section class=\"ftco-section\" id=\"blog-section\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <div class=\"row justify-content-center mb-5 pb-5\">\r\n");
      out.write("          <div class=\"col-md-10 heading-section text-center ftco-animate\">\r\n");
      out.write("            <span class=\"subheading\"></span>\r\n");
      out.write("            <h2 class=\"mb-4\">특허 검색</h2>\r\n");
      out.write("            <p>산업분야 검색, 단어 검색 등을 지원합니다.</p><br>\r\n");
      out.write("            <hr class=\"hr_navy\">\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("          <div class=\"main_table\">\r\n");
      out.write("   <div class=\"search-container\">\r\n");
      out.write("  <form>\r\n");
      out.write("       <label for=\"patent-type\" class=\"col-sm-2 col-form-label\">특허 산업분야</label>\r\n");
      out.write("                        <select id=\"patentType\" name=\"patentType\">\r\n");
      out.write("                            <option value=\"none\" selected>[필수선택] 산업분야를 선택하세요</option>\r\n");
      out.write("                            <option value=\"\">고무 제품 및 플라스틱 제품 제조업</option>\r\n");
      out.write("                            <option value=\"\">기초 화학물질 제조업</option>\r\n");
      out.write("                            <option value=\"\">마그네틱 및 광학 매체 제조업</option>\r\n");
      out.write("                            <option value=\"\">반도체 제조업</option>\r\n");
      out.write("                            <option value=\"\">안경, 사진장비 및 기타 광학기기 제조업</option>\r\n");
      out.write("                            <option value=\"patentType1\">영상 및 음향기기 제조업</option>\r\n");
      out.write("                            <option value=\"\">의료용 기기 제조업</option>\r\n");
      out.write("                            <option value=\"\">자동차 제조업</option>\r\n");
      out.write("                            <option value=\"\">전구 및 조명장치 제조업</option>\r\n");
      out.write("                            <option value=\"\">전동기, 발전기 및 전기 변환, 공급, 제어 장치 제조업</option>\r\n");
      out.write("                            <option value=\"\">전자부품 제조업</option>\r\n");
      out.write("                            <option value=\"\">절연선 및 케이블 제조업</option>\r\n");
      out.write("                            <option value=\"\">컴퓨터 및 주변장치 제조업</option>\r\n");
      out.write("                            <option value=\"patentType2\">컴퓨터 프로그래밍 및 정보서비스업</option>\r\n");
      out.write("                            <option value=\"patentType3\">통신 및 방송 장비 제조업</option>\r\n");
      out.write("                            <option value=\"\">특수 기계 제조업</option>\r\n");
      out.write("                            <option value=\"\">기타 전기장비 제조업</option>\r\n");
      out.write("                            <option value=\"\">기타 제품 제조업</option>\r\n");
      out.write("                            <option value=\"etc\">기타 산업분야</option>\r\n");
      out.write("                        </select>&nbsp;&nbsp;&nbsp;\r\n");
      out.write("      <label for=\"patent-option\" class=\"col-sm-2 col-form-label\">특허 검색옵션</label>\r\n");
      out.write("      <select id=\"searchItem\" name=\"searchItem\">\r\n");
      out.write("      <option value=\"onlypatenttype\" >구분</option>\r\n");
      out.write("      \t<option value=\"onlypatenttype\" >특허 산업분야만 검색</option>\r\n");
      out.write("          <option value=\"patentName\" >특허명</option>\r\n");
      out.write("          <option value=\"patentHolderName\" >특허 보유자명(개인/기업)</option>\r\n");
      out.write("          <option value=\"patentContent\" >특허설명</option>\r\n");
      out.write("      </select><br><br>\r\n");
      out.write("      <label for=\"patent-word\" class=\"col-sm-2 col-form-label\">검색</label>\r\n");
      out.write("      <input type=\"text\" class=\"patent-word\" name=\"searchWord\" id=\"searchWord\">&nbsp;&nbsp;&nbsp;\r\n");
      out.write("      <button type=\"button\" id=\"patentBtn\" class=\"btn btn-outline-primary btn-rounded waves-effect\">검색하기</button>\r\n");
      out.write("  </form>\r\n");
      out.write("  <hr class=\"hr_navy\">\r\n");
      out.write("   </div>\r\n");
      out.write("    <!--검색 결과는 검색하기 버튼 누르고 난 후에 떠야 합니다,,,(with.Ajax) 이 테이블은 그저 예시일 뿐-->\r\n");
      out.write("        <div class=\"search-result\" id=\"section-bar-patent\">\r\n");
      out.write(" \r\n");
      out.write("              <!--페이징 & 검색-->\r\n");
      out.write("  <div class=\"page-center\">\r\n");
      out.write("  \r\n");
      out.write("  <nav>\r\n");
      out.write("  <ul class=\"pagination justify-content-center\">\r\n");
      out.write("    <li class=\"page-item\">\r\n");
      out.write("      <a class=\"page-link\" aria-label=\"Previous\">\r\n");
      out.write("        <span aria-hidden=\"true\">&laquo;</span>\r\n");
      out.write("        <span class=\"sr-only\">Previous</span>\r\n");
      out.write("      </a>\r\n");
      out.write("    </li>\r\n");
      out.write("    <li class=\"page-item active\"><a class=\"page-link\">1</a></li>\r\n");
      out.write("    <li class=\"page-item\"><a class=\"page-link\">2</a></li>\r\n");
      out.write("    <li class=\"page-item\"><a class=\"page-link\">3</a></li>\r\n");
      out.write("    <li class=\"page-item\"><a class=\"page-link\">4</a></li>\r\n");
      out.write("    <li class=\"page-item\"><a class=\"page-link\">5</a></li>\r\n");
      out.write("    <li class=\"page-item\">\r\n");
      out.write("      <a class=\"page-link\" aria-label=\"Next\">\r\n");
      out.write("        <span aria-hidden=\"true\">&raquo;</span>\r\n");
      out.write("        <span class=\"sr-only\">Next</span>\r\n");
      out.write("      </a>\r\n");
      out.write("    </li>\r\n");
      out.write("  </ul>\r\n");
      out.write("</nav>\r\n");
      out.write("      </div>\r\n");
      out.write("        </div>\r\n");
      out.write("         <hr class=\"hr_navy\">\r\n");
      out.write("          </div>\r\n");
      out.write("          </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("    <footer class=\"ftco-footer ftco-section\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row mb-5\">\r\n");
      out.write("                <div class=\"col-md\">\r\n");
      out.write("                    <div class=\"ftco-footer-widget mb-4\">\r\n");
      out.write("                        <h2 class=\"ftco-heading-2\">About <span>SupporterS</span></h2>\r\n");
      out.write("                        <p>창업자가 궁금해하는 것, <br>필요로 하는 것, <br>필요로 할 것들을 최대한 지원하기 위해 만든 사이트입니다.</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md\">\r\n");
      out.write("                    <div class=\"ftco-footer-widget mb-4 ml-md-4\">\r\n");
      out.write("                        <h2 class=\"ftco-heading-2\">바로가기</h2>\r\n");
      out.write("                        <ul class=\"list-unstyled\">\r\n");
      out.write("                            <li><a href=\"/cloud/home\"><span class=\"icon-long-arrow-right mr-2\"></span>Home</a></li>\r\n");
      out.write("                            <li><a href=\"/cloud/member/goPatent\"><span class=\"icon-long-arrow-right mr-2\"></span>검색 및 특허 관련</a></li>\r\n");
      out.write("                            <li><a href=\"/cloud/board/boardListForm\"><span class=\"icon-long-arrow-right mr-2\"></span>Q & A 게시판</a></li>\r\n");
      out.write("                            <li><a href=\"/cloud/survey/surveyListForm\"><span class=\"icon-long-arrow-right mr-2\"></span>블라인드 테스트</a></li>\r\n");
      out.write("                            <li><a href=\"/cloud/funding/fundingListForm\"><span class=\"icon-long-arrow-right mr-2\"></span>크라우드 펀딩</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md\">\r\n");
      out.write("                    <div class=\"ftco-footer-widget mb-4\">\r\n");
      out.write("                        <h2 class=\"ftco-heading-2\">검색 및 특허 관련</h2>\r\n");
      out.write("                        <ul class=\"list-unstyled\">\r\n");
      out.write("                            <li><a href=\"/cloud/member/searchGo\"><span class=\"icon-long-arrow-right mr-2\"> 특허 검색</span></a></li>\r\n");
      out.write("                            <li><a href=\"/cloud/item/searchItem\"><span class=\"icon-long-arrow-right mr-2\"> 제품 검색</span></a></li>\r\n");
      out.write("                            <li><a href=\"/cloud/member/goPatent\"><span class=\"icon-long-arrow-right mr-2\"> 특허 출원 신청</span></a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md\">\r\n");
      out.write("                    <div class=\"ftco-footer-widget mb-4\">\r\n");
      out.write("                        <h2 class=\"ftco-heading-2\">찾아오는 길</h2>\r\n");
      out.write("                        <div class=\"block-23 mb-0\">\r\n");
      out.write("                            <ul>\r\n");
      out.write("                                <li><span class=\"icon icon-map-marker\"></span><span class=\"text\">4th floor, 513, Yeongdong-daero, Gangnam-gu, Seoul, Republic of Korea</span></li>\r\n");
      out.write("                                <li><a href=\"#\"><span class=\"icon icon-phone\"></span><span class=\"text\">+82 02 6000 0114</span></a></li>\r\n");
      out.write("                                <li><a href=\"#\"><span class=\"icon icon-envelope\"></span><span class=\"text\">info@yourdomain.com</span></a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </footer>\r\n");
      out.write("    \r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("  <!-- loader -->\r\n");
      out.write("  <div id=\"ftco-loader\" class=\"show fullscreen\"><svg class=\"circular\" width=\"48px\" height=\"48px\"><circle class=\"path-bg\" cx=\"24\" cy=\"24\" r=\"22\" fill=\"none\" stroke-width=\"4\" stroke=\"#eeeeee\"/><circle class=\"path\" cx=\"24\" cy=\"24\" r=\"22\" fill=\"none\" stroke-width=\"4\" stroke-miterlimit=\"10\" stroke=\"#F96D00\"/></svg></div>\r\n");
      out.write("\r\n");
      out.write("<!-- Modal -->\r\n");
      out.write("    <div class=\"modal fade show\" id=\"exampleModal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"exampleModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("    <div class=\"modal-dialog\" role=\"document\">\r\n");
      out.write("        <div class=\"modal-content\">\r\n");
      out.write("            <div class=\"modal-header\">\r\n");
      out.write("                <h4 class=\"modal-title\" id=\"exampleModalLabel\">특허 사용 허가 신청서</h4>\r\n");
      out.write("                <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\r\n");
      out.write("                    <span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("                </button>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"modal-body\">\r\n");
      out.write("                <form action=\"/cloud/member/permitForm\" method=\"post\" id=\"permitForm\">\r\n");
      out.write("              <div class=\"form-group\">\r\n");
      out.write("                <label for=\"appointment_name\" class=\"text-black\">신청인</label>\r\n");
      out.write("                <input type=\"text\" class=\"form-control\" name=\"memberId\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.loginId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" id=\"memId\" placeholder=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.loginId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" readonly=\"readonly\">\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"form-group\">\r\n");
      out.write("                <label for=\"appointment_patentnum\" class=\"text-black\">특허번호</label>\r\n");
      out.write("                <input type=\"text\" class=\"form-control\" name=\"patentNum\" value=\"\" id=\"patentNum\" placeholder=\"\" readonly=\"readonly\">\r\n");
      out.write("              </div>\r\n");
      out.write("              \r\n");
      out.write("              <label for=\"item-option\" class=\"text-black\">특허 검색옵션<label>\r\n");
      out.write("              <select id=\"item-option\" name=\"itemNum\">\r\n");
      out.write("              <option value=\"none\" selected>특허에 사용할 제품/서비스를 선택해주세요</option>\r\n");
      out.write("              <!--  <option value=\"\">itemName_1</option>-->\r\n");
      out.write("              </select><br><br>\r\n");
      out.write("              \r\n");
      out.write("               <div class=\"form-group\">\r\n");
      out.write("                    <label for=\"appointment_file\" class=\"text-black\">특허 사용 신청서</label>\r\n");
      out.write("                    <input type=\"file\" class=\"form-control\" name=\"upload\" id=\"upload\" multiple />\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"form-group\">\r\n");
      out.write("                    <label for=\"appointment_file2\" class=\"text-black\">특허 사용 허가서</label>\r\n");
      out.write("                    <input type=\"file\" class=\"form-control\" name=\"upload1\" id=\"upload1\" multiple />\r\n");
      out.write("                  </div>\r\n");
      out.write("              \r\n");
      out.write("              \r\n");
      out.write("\r\n");
      out.write("              <!--<div class=\"form-group\">\r\n");
      out.write("                <label for=\"appointment_message\" class=\"text-black\">Message</label>\r\n");
      out.write("                <textarea name=\"\" id=\"appointment_message\" class=\"form-control\" cols=\"30\" rows=\"10\"></textarea>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"form-group\">\r\n");
      out.write("                <input type=\"submit\" value=\"Send Message\" class=\"btn btn-primary\">\r\n");
      out.write("              </div>-->\r\n");
      out.write("            </form>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"modal-footer\">\r\n");
      out.write("            ");
      if (_jspx_meth_c_005fif_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                <button type=\"button\" class=\"btn btn-outline-success\" data-dismiss=\"modal\">닫기</button>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("  <script src=\"/cloud/resources/js/jquery.min.js\"></script>\r\n");
      out.write("  <script src=\"/cloud/resources/js/jquery-migrate-3.0.1.min.js\"></script>\r\n");
      out.write("  <script src=\"/cloud/resources/js/popper.min.js\"></script>\r\n");
      out.write("  <script src=\"//netdna.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js\"></script>\r\n");
      out.write("  <script src=\"/cloud/resources/js/jquery.easing.1.3.js\"></script>\r\n");
      out.write("  <script src=\"/cloud/resources/js/jquery.waypoints.min.js\"></script>\r\n");
      out.write("  <script src=\"/cloud/resources/js/jquery.stellar.min.js\"></script>\r\n");
      out.write("  <script src=\"/cloud/resources/js/owl.carousel.min.js\"></script>\r\n");
      out.write("  <script src=\"/cloud/resources/js/jquery.magnific-popup.min.js\"></script>\r\n");
      out.write("  <script src=\"/cloud/resources/js/aos.js\"></script>\r\n");
      out.write("  <script src=\"/cloud/resources/js/jquery.animateNumber.min.js\"></script>\r\n");
      out.write("  <script src=\"/cloud/resources/js/scrollax.min.js\"></script>\r\n");
      out.write("  \r\n");
      out.write("  <script src=\"/cloud/resources/js/main.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("  </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/search/search_patent.jsp(322,7) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.loginId==null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t  \t\t\t <li style=\"margin-left: 20px;\" class=\"nav-item cta\">\r\n");
          out.write("                    <div class=\"dropdown show\">\r\n");
          out.write("                        <a class=\"btn btn-primary py-3 px-4\" href=\"#\" role=\"button\" id=\"dropdownMenuLink\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
          out.write("                            <span class=\"member-btn\">로그인/회원가입</span>\r\n");
          out.write("                        </a>\r\n");
          out.write("\r\n");
          out.write("                        <div class=\"dropdown-menu\" aria-labelledby=\"dropdownMenuLink\">\r\n");
          out.write("                            <a class=\"dropdown-item\" href=\"/cloud/member/gologin\"><span class=\"member-btn\">로그인</span></a>\r\n");
          out.write("                            <a class=\"dropdown-item\" href=\"/cloud/member/gosign\"><span class=\"member-btn\">회원가입</span></a>\r\n");
          out.write("                            <a class=\"dropdown-item\" href=\"/cloud/member/gofindid\"><span class=\"member-btn\">아이디/비밀번호 찾기</span></a>\r\n");
          out.write("                        </div>\r\n");
          out.write("                    </div>\r\n");
          out.write("                    </li>\r\n");
          out.write("\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /WEB-INF/views/search/search_patent.jsp(338,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.loginId!=null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t<li style=\"margin-left: 20px;\" class=\"nav-item cta\">\r\n");
          out.write("\t\t\t\t<div class=\"dropdown show\">\r\n");
          out.write("                        <a class=\"btn btn-primary py-3 px-4\" href=\"#\" role=\"button\" id=\"dropdownMenuLink\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
          out.write("                            <span class=\"member-btn\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.loginName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write(' ');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.loginType}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("님</span>\r\n");
          out.write("                        </a>\r\n");
          out.write("\r\n");
          out.write("                        <div class=\"dropdown-menu\" aria-labelledby=\"dropdownMenuLink\">\r\n");
          out.write("                            <a class=\"dropdown-item\" href=\"/cloud/member/goMypage\">마이페이지</a>\r\n");
          out.write("                            <a class=\"dropdown-item\" href=\"/cloud/member/goupdate\">회원 정보 수정</a>\r\n");
          out.write("                            <a class=\"dropdown-item\" href=\"/cloud/member/logout\">로그아웃</a>\r\n");
          out.write("                        </div>\r\n");
          out.write("                    </div>\r\n");
          out.write("\t\t\t\t</li>\r\n");
          out.write("\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent(null);
      // /WEB-INF/views/search/search_patent.jsp(558,12) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.loginType == 'inventor' || sessionScope.loginType == 'enp'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                <button type=\"button\" id=\"permitBtn\" class=\"btn btn-outline-info\">신청하기</button>\r\n");
          out.write("                ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
    }
    return false;
  }
}
