package aaa;

import java.io.Serializable;
import java.util.Date;

/**
 * 클라우드펀딩 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class CloudfundingAaa implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** Couldfunding_seq. */
	private Integer couldfundingnum;

	/** ITEM. */
	private ItemAaa item;

	/** 펀딩목표금액. */
	private Integer itemgoalprice;

	/** 현재펀딩금액. */
	private Integer itemcurrecyprice;

	/** 펀딩마감일자. */
	private Date fundingduedate;

	/**
	 * 생성자.
	 */
	public CloudfundingAaa() {
	}

	/**
	 * Couldfunding_seq을 설정합니다..
	 * 
	 * @param couldfundingnum
	 *            Couldfunding_seq
	 */
	public void setCouldfundingnum(Integer couldfundingnum) {
		this.couldfundingnum = couldfundingnum;
	}

	/**
	 * Couldfunding_seq을 가져옵니다..
	 * 
	 * @return Couldfunding_seq
	 */
	public Integer getCouldfundingnum() {
		return this.couldfundingnum;
	}

	/**
	 * ITEM을 설정합니다..
	 * 
	 * @param item
	 *            ITEM
	 */
	public void setItem(ItemAaa item) {
		this.item = item;
	}

	/**
	 * ITEM을 가져옵니다..
	 * 
	 * @return ITEM
	 */
	public ItemAaa getItem() {
		return this.item;
	}

	/**
	 * 펀딩목표금액을 설정합니다..
	 * 
	 * @param itemgoalprice
	 *            펀딩목표금액
	 */
	public void setItemgoalprice(Integer itemgoalprice) {
		this.itemgoalprice = itemgoalprice;
	}

	/**
	 * 펀딩목표금액을 가져옵니다..
	 * 
	 * @return 펀딩목표금액
	 */
	public Integer getItemgoalprice() {
		return this.itemgoalprice;
	}

	/**
	 * 현재펀딩금액을 설정합니다..
	 * 
	 * @param itemcurrecyprice
	 *            현재펀딩금액
	 */
	public void setItemcurrecyprice(Integer itemcurrecyprice) {
		this.itemcurrecyprice = itemcurrecyprice;
	}

	/**
	 * 현재펀딩금액을 가져옵니다..
	 * 
	 * @return 현재펀딩금액
	 */
	public Integer getItemcurrecyprice() {
		return this.itemcurrecyprice;
	}

	/**
	 * 펀딩마감일자을 설정합니다..
	 * 
	 * @param fundingduedate
	 *            펀딩마감일자
	 */
	public void setFundingduedate(Date fundingduedate) {
		this.fundingduedate = fundingduedate;
	}

	/**
	 * 펀딩마감일자을 가져옵니다..
	 * 
	 * @return 펀딩마감일자
	 */
	public Date getFundingduedate() {
		return this.fundingduedate;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((couldfundingnum == null) ? 0 : couldfundingnum.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		CloudfundingAaa other = (CloudfundingAaa) obj;
		if (couldfundingnum == null) {
			if (other.couldfundingnum != null) {
				return false;
			}
		} else if (!couldfundingnum.equals(other.couldfundingnum)) {
			return false;
		}
		return true;
	}

}
