package aaa;

import java.io.Serializable;

/**
 * PATENTSUB 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class PatentsubAaa implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** Patentsub_seq. */
	private Integer patentsubnum;

	/** PATENT. */
	private PatentAaa patent;

	/** 가계약서. */
	private String documentfilename;

	/** saveDocumentFilename. */
	private String savedocumentfilename;

	/** 특허정보(파일). */
	private String referencefilename;

	/** saveReferenceFilename. */
	private String savereferencefilename;

	/**
	 * 생성자.
	 */
	public PatentsubAaa() {
	}

	/**
	 * Patentsub_seq을 설정합니다..
	 * 
	 * @param patentsubnum
	 *            Patentsub_seq
	 */
	public void setPatentsubnum(Integer patentsubnum) {
		this.patentsubnum = patentsubnum;
	}

	/**
	 * Patentsub_seq을 가져옵니다..
	 * 
	 * @return Patentsub_seq
	 */
	public Integer getPatentsubnum() {
		return this.patentsubnum;
	}

	/**
	 * PATENT을 설정합니다..
	 * 
	 * @param patent
	 *            PATENT
	 */
	public void setPatent(PatentAaa patent) {
		this.patent = patent;
	}

	/**
	 * PATENT을 가져옵니다..
	 * 
	 * @return PATENT
	 */
	public PatentAaa getPatent() {
		return this.patent;
	}

	/**
	 * 가계약서을 설정합니다..
	 * 
	 * @param documentfilename
	 *            가계약서
	 */
	public void setDocumentfilename(String documentfilename) {
		this.documentfilename = documentfilename;
	}

	/**
	 * 가계약서을 가져옵니다..
	 * 
	 * @return 가계약서
	 */
	public String getDocumentfilename() {
		return this.documentfilename;
	}

	/**
	 * saveDocumentFilename을 설정합니다..
	 * 
	 * @param savedocumentfilename
	 *            saveDocumentFilename
	 */
	public void setSavedocumentfilename(String savedocumentfilename) {
		this.savedocumentfilename = savedocumentfilename;
	}

	/**
	 * saveDocumentFilename을 가져옵니다..
	 * 
	 * @return saveDocumentFilename
	 */
	public String getSavedocumentfilename() {
		return this.savedocumentfilename;
	}

	/**
	 * 특허정보(파일)을 설정합니다..
	 * 
	 * @param referencefilename
	 *            특허정보(파일)
	 */
	public void setReferencefilename(String referencefilename) {
		this.referencefilename = referencefilename;
	}

	/**
	 * 특허정보(파일)을 가져옵니다..
	 * 
	 * @return 특허정보(파일)
	 */
	public String getReferencefilename() {
		return this.referencefilename;
	}

	/**
	 * saveReferenceFilename을 설정합니다..
	 * 
	 * @param savereferencefilename
	 *            saveReferenceFilename
	 */
	public void setSavereferencefilename(String savereferencefilename) {
		this.savereferencefilename = savereferencefilename;
	}

	/**
	 * saveReferenceFilename을 가져옵니다..
	 * 
	 * @return saveReferenceFilename
	 */
	public String getSavereferencefilename() {
		return this.savereferencefilename;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((patentsubnum == null) ? 0 : patentsubnum.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		PatentsubAaa other = (PatentsubAaa) obj;
		if (patentsubnum == null) {
			if (other.patentsubnum != null) {
				return false;
			}
		} else if (!patentsubnum.equals(other.patentsubnum)) {
			return false;
		}
		return true;
	}

}
