package aaa;

import java.io.Serializable;

/**
 * 브릿지테이블(아이템, 특허j) 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class PtiAaa implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** PTI_seq. */
	private Integer ptiSeq;

	/** ITEM. */
	private ItemAaa item;

	/** PATENT. */
	private PatentAaa patent;

	/**
	 * 생성자.
	 */
	public PtiAaa() {
	}

	/**
	 * PTI_seq을 설정합니다..
	 * 
	 * @param ptiSeq
	 *            PTI_seq
	 */
	public void setPtiSeq(Integer ptiSeq) {
		this.ptiSeq = ptiSeq;
	}

	/**
	 * PTI_seq을 가져옵니다..
	 * 
	 * @return PTI_seq
	 */
	public Integer getPtiSeq() {
		return this.ptiSeq;
	}

	/**
	 * ITEM을 설정합니다..
	 * 
	 * @param item
	 *            ITEM
	 */
	public void setItem(ItemAaa item) {
		this.item = item;
	}

	/**
	 * ITEM을 가져옵니다..
	 * 
	 * @return ITEM
	 */
	public ItemAaa getItem() {
		return this.item;
	}

	/**
	 * PATENT을 설정합니다..
	 * 
	 * @param patent
	 *            PATENT
	 */
	public void setPatent(PatentAaa patent) {
		this.patent = patent;
	}

	/**
	 * PATENT을 가져옵니다..
	 * 
	 * @return PATENT
	 */
	public PatentAaa getPatent() {
		return this.patent;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((ptiSeq == null) ? 0 : ptiSeq.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		PtiAaa other = (PtiAaa) obj;
		if (ptiSeq == null) {
			if (other.ptiSeq != null) {
				return false;
			}
		} else if (!ptiSeq.equals(other.ptiSeq)) {
			return false;
		}
		return true;
	}

}
