package aaa;

import java.io.Serializable;
import java.util.Date;

/**
 * 댓글 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class ReplyAaa implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** reply_seq. */
	private Integer replynum;

	/** Q&A게시판. */
	private BoardAaa board;

	/** 내용. */
	private String reply;

	/** 댓글작성일. */
	private Date replydate;

	/** id. */
	private String id;

	/**
	 * 생성자.
	 */
	public ReplyAaa() {
	}

	/**
	 * reply_seq을 설정합니다..
	 * 
	 * @param replynum
	 *            reply_seq
	 */
	public void setReplynum(Integer replynum) {
		this.replynum = replynum;
	}

	/**
	 * reply_seq을 가져옵니다..
	 * 
	 * @return reply_seq
	 */
	public Integer getReplynum() {
		return this.replynum;
	}

	/**
	 * Q&A게시판을 설정합니다..
	 * 
	 * @param board
	 *            Q&A게시판
	 */
	public void setBoard(BoardAaa board) {
		this.board = board;
	}

	/**
	 * Q&A게시판을 가져옵니다..
	 * 
	 * @return Q&A게시판
	 */
	public BoardAaa getBoard() {
		return this.board;
	}

	/**
	 * 내용을 설정합니다..
	 * 
	 * @param reply
	 *            내용
	 */
	public void setReply(String reply) {
		this.reply = reply;
	}

	/**
	 * 내용을 가져옵니다..
	 * 
	 * @return 내용
	 */
	public String getReply() {
		return this.reply;
	}

	/**
	 * 댓글작성일을 설정합니다..
	 * 
	 * @param replydate
	 *            댓글작성일
	 */
	public void setReplydate(Date replydate) {
		this.replydate = replydate;
	}

	/**
	 * 댓글작성일을 가져옵니다..
	 * 
	 * @return 댓글작성일
	 */
	public Date getReplydate() {
		return this.replydate;
	}

	/**
	 * id을 설정합니다..
	 * 
	 * @param id
	 *            id
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * id을 가져옵니다..
	 * 
	 * @return id
	 */
	public String getId() {
		return this.id;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((replynum == null) ? 0 : replynum.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		ReplyAaa other = (ReplyAaa) obj;
		if (replynum == null) {
			if (other.replynum != null) {
				return false;
			}
		} else if (!replynum.equals(other.replynum)) {
			return false;
		}
		return true;
	}

}
