/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.21
 * Generated at: 2019-10-05 10:43:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Board_005fDetail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1562034500000L));
    _jspx_dependants.put("jar:file:/C:/Users/창민/Documents/GitHub/GoodDeV/ChanMin/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/GoodDeV/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <title>SupporterS :: Board Read</title>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("    <script src=\"/cloud/resources/js/jquery-3.4.1.min.js\"></script>\r\n");
      out.write("    <script src=\"/cloud/resources/js/jquery-ui.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/cloud/resources/css/open-iconic-bootstrap.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/cloud/resources/css/animate.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/cloud/resources/css/owl.carousel.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/cloud/resources/css/owl.theme.default.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/cloud/resources/css/magnific-popup.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/cloud/resources/css/aos.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/cloud/resources/css/ionicons.min.css\">\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/cloud/resources/css/flaticon.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/cloud/resources/css/icomoon.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/cloud/resources/css/style.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/cloud/resources/css/Board.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/cloud/resources/css/new-comment.css\">\r\n");
      out.write("    \r\n");
      out.write("    <script>\r\n");
      out.write("    $(function(){\r\n");
      out.write("    \t\r\n");
      out.write("    });\r\n");
      out.write("    </script>\r\n");
      out.write("    \r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body data-spy=\"scroll\" data-target=\".site-navbar-target\" data-offset=\"300\">\r\n");
      out.write("\r\n");
      out.write("    <nav class=\"navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light site-navbar-target\" id=\"ftco-navbar\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <a class=\"navbar-brand\" href=\"/cloud/home\">SupporterS</a>\r\n");
      out.write("            <button class=\"navbar-toggler js-fh5co-nav-toggle fh5co-nav-toggle\" type=\"button\" data-toggle=\"collapse\" data-target=\"#ftco-nav\" aria-controls=\"ftco-nav\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("                <span class=\"oi oi-menu\"></span> Menu\r\n");
      out.write("            </button>\r\n");
      out.write("            <div class=\"collapse navbar-collapse\" id=\"ftco-nav\">\r\n");
      out.write("                <ul class=\"navbar-nav nav ml-auto\">\r\n");
      out.write("                    <li class=\"nav-item\"><a href=\"/cloud/home\" class=\"nav-link\"><span>Home</span></a></li>\r\n");
      out.write("                    <li class=\"nav-item\"><a href=\"/cloud/member/goPatent\" class=\"nav-link\"><span>특허 / 검색</span></a></li>\r\n");
      out.write("                    <li class=\"nav-item\"><a href=\"/cloud/board/boardListForm\" class=\"nav-link\"><span>Q & A 게시판</span></a></li>\r\n");
      out.write("                    <li class=\"nav-item\"><a href=\"/cloud/survey/goSurvey_list\" class=\"nav-link\"><span>블라인드 테스트</span></a></li>\r\n");
      out.write("                    <li class=\"nav-item\"><a href=\"/cloud/funding/gofunding\" class=\"nav-link\"><span>크라우드 펀딩</span></a></li>\r\n");
      out.write("                    ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    ");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("\r\n");
      out.write("    <section class=\"hero-wrap hero-wrap-2\" style=\"background-image: url('/cloud/resources/images/about_6.jpg');\" data-stellar-background-ratio=\"0.5\">\r\n");
      out.write("        <div class=\"overlay\"></div>\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row no-gutters slider-text align-items-end justify-content-center\">\r\n");
      out.write("                <div class=\"col-md-9 ftco-animate pb-5 text-center\">\r\n");
      out.write("                    <h1 class=\"mb-3 bread\">Q & A Board</h1>\r\n");
      out.write("                    <p class=\"breadcrumbs\"><span class=\"mr-2\"><a href=\"home\">Home <i class=\"ion-ios-arrow-forward\"></i></a></span> <span class=\"mr-2\"><a href=\"goBoardlist\">Q & A 게시판 <i class=\"ion-ios-arrow-forward\"></i></a></span> <span>게시글 상세보기 <i class=\"ion-ios-arrow-forward\"></i></span></p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <section class=\"ftco-section\" id=\"blog-section\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row justify-content-center mb-5 pb-5\">\r\n");
      out.write("                <div class=\"col-md-10 heading-section text-center ftco-animate\">\r\n");
      out.write("                    <span class=\"subheading\"></span>\r\n");
      out.write("                    <h2 class=\"mb-4\">Q & A 게시판</h2>\r\n");
      out.write("                    <p>궁금한 것을 자유롭게 묻고 답할 수 있습니다.</p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"Detail_table ftco-animate\">\r\n");
      out.write("                <form action=\"update?\" method=\"post\" id=\"\">\r\n");
      out.write("                    <div class=\"form-group row\">\r\n");
      out.write("                        <label for=\"\" class=\"col-sm-2 col-form-label\"><span><b>작성 날짜</b></span></label>\r\n");
      out.write("                        <div class=\"col-sm-10\">\r\n");
      out.write("                            <input type=\"text\" class=\"form-control\" name=\"boardDate\" id=\"\" placeholder=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.boardDate}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" readonly=\"readonly\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-group row\">\r\n");
      out.write("                        <label for=\"\" class=\"col-sm-2 col-form-label\"><span><b>작성자</b></span></label>\r\n");
      out.write("                        <div class=\"col-sm-10\">\r\n");
      out.write("                            <input type=\"text\" class=\"form-control\" name=\"memberId\" id=\"\" placeholder=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.memberId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" readonly=\"readonly\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"form-group row\">\r\n");
      out.write("                        <label for=\"\" class=\"col-sm-2 col-form-label\"><span><b>질문\r\n");
      out.write("                                    분류</b></span></label>\r\n");
      out.write("                        <div class=\"col-sm-10\">\r\n");
      out.write("                            <input type=\"text\" class=\"form-control\" name=\"qCategory\" id=\"\" placeholder=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.qCategory}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" readonly=\"readonly\">\r\n");
      out.write("                            <!-- <input type=\"email\" class=\"form-control\" id=\"inputEmail3\" placeholder=\"Email\">-->\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"form-group row\">\r\n");
      out.write("                        <label for=\"\" class=\"col-sm-2 col-form-label\"><span><b>제목</b></span></label>\r\n");
      out.write("                        <div class=\"col-sm-10\">\r\n");
      out.write("                            <input type=\"text\" class=\"form-control\" name=\"title\" id=\"\" placeholder=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.title}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" readonly=\"readonly\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-group row\">\r\n");
      out.write("                        <label for=\"\" class=\"col-sm-2 col-form-label\"><span><b>내용</b></span></label>\r\n");
      out.write("                        <div class=\"col-sm-10\">\r\n");
      out.write("                            <textarea rows=\"8\" cols=\"112\" readonly=\"readonly\" name=\"content\" class=\"form-control\" placeholder=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.content}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"></textarea>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-group row\">\r\n");
      out.write("                        <label for=\"\" class=\"col-sm-2 col-form-label\"><span><b>첨부파일</b></span></label>\r\n");
      out.write("                        <div class=\"col-sm-10\">\r\n");
      out.write("                            <input type=\"file\" class=\"form-control\" name=\"saveFilename\" id=\"saveFilename\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    </form>\r\n");
      out.write("                    \r\n");
      out.write("                    <div class=\"form-group row\">\r\n");
      out.write("                <div class=\"col-sm-10\">\r\n");
      out.write("                    <div style=\"margin-top: 40px;\">\r\n");
      out.write("                        <a href=\"/cloud/board/boardListForm\" class=\"btns btn-3\"><span class=\"white\">돌아가기</span></a>\r\n");
      out.write("                        &nbsp;&nbsp;\r\n");
      out.write("                        ");
      out.write("\r\n");
      out.write("                        <a href=\"/cloud/board/goupdate?boardNum=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.boardNum}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" class=\"btns btn-3-green\"><span class=\"white\">수정</span></a>\r\n");
      out.write("                        &nbsp;&nbsp;\r\n");
      out.write("                        <a href=\"/cloud/board/godelete?boardNum=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.boardNum}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" class=\"btns btn-3-red\"><span class=\"white\">삭제</span></a>\r\n");
      out.write("                        ");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("                    \r\n");
      out.write("                    <hr class=\"hr_purple\">\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"container\" id=\"chat-container\">\r\n");
      out.write("                        <!-- <h2 class=\"page-header\">Comments</h2> -->\r\n");
      out.write("                        <div class=\"comment-list\">\r\n");
      out.write("\r\n");
      out.write("                            <!-- other Comment -->\r\n");
      out.write("                            <article class=\"row\">\r\n");
      out.write("                                <div class=\"col-md-10 col-sm-10\">\r\n");
      out.write("                                    <div class=\"panel panel-default\">\r\n");
      out.write("                                        <div class=\"panel-body\">\r\n");
      out.write("                                            <header class=\"text-left\">\r\n");
      out.write("\r\n");
      out.write("                                                <!-- 댓글은 memberId 필요  -->\r\n");
      out.write("                                                <div class=\"comment-user\"><i class=\"fa fa-user\"></i> [memberId]</div>\r\n");
      out.write("                                                <time class=\"comment-date\" datetime=\"\"><i class=\"fa fa-clock-o\"></i> 2019-10-02 | 14:29</time>\r\n");
      out.write("\r\n");
      out.write("                                            </header>\r\n");
      out.write("                                            <div class=\"comment-post\">\r\n");
      out.write("                                                <p>\r\n");
      out.write("                                                    [다른 사람들이 입력한 내용은 여기서 나오게끔]\r\n");
      out.write("                                                </p>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <p class=\"text-right\">\r\n");
      out.write("                                            <input type=\"text\" class=\"searchWord\" placeholder=\" 답글을 입력하세요\">\r\n");
      out.write("                                            <a href=\"#\" class=\"btn btn-outline-primary\">\r\n");
      out.write("                                            <i class=\"fa fa-reply\"></i> 답글달기</a></p>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <hr>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </article>\r\n");
      out.write("\r\n");
      out.write("                            <!-- 답글 쪽 article은 이렇게 -->\r\n");
      out.write("                            <article class=\"row\">\r\n");
      out.write("                                <div class=\"col-md-2 col-sm-2\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"col-md-9 col-sm-9\">\r\n");
      out.write("                                    <div class=\"panel panel-default\">\r\n");
      out.write("                                        <div class=\"panel-body\">\r\n");
      out.write("                                            <header class=\"text-left\">\r\n");
      out.write("                                                <div class=\"comment-user\"><i class=\"fa fa-user\"></i> [memberId]</div>\r\n");
      out.write("                                                <time class=\"comment-date\" datetime=\"16-12-2014 01:05\"><i class=\"fa fa-clock-o\"></i> 2019-10-02 | 14:57</time>\r\n");
      out.write("                                            </header>\r\n");
      out.write("                                            <div class=\"comment-post\">\r\n");
      out.write("                                                <p>\r\n");
      out.write("                                                    [...]\r\n");
      out.write("                                                </p>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <p class=\"text-right\">\r\n");
      out.write("                                            <input type=\"text\" class=\"searchWord\" placeholder=\" 답글을 입력하세요\">\r\n");
      out.write("                                            <a href=\"#\" class=\"btn btn-outline-primary\">\r\n");
      out.write("                                            <i class=\"fa fa-reply\"></i> 답글달기</a></p>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <hr>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </article>\r\n");
      out.write("\r\n");
      out.write("                            <!-- my Comment -->\r\n");
      out.write("                            <article class=\"row\">\r\n");
      out.write("                                <div class=\"col-md-10 col-sm-10\">\r\n");
      out.write("                                    <div class=\"panel panel-default\">\r\n");
      out.write("                                        <div class=\"panel-body\">\r\n");
      out.write("                                            <header class=\"text-right\">\r\n");
      out.write("                                                <div class=\"comment-user\"><i class=\"fa fa-user\"></i> [내 댓글]</div>\r\n");
      out.write("                                                <time class=\"comment-date\" datetime=\"\"><i class=\"fa fa-clock-o\"></i> 2019-10-02 | 14:29</time>\r\n");
      out.write("                                            </header>\r\n");
      out.write("                                            <div class=\"comment-post\">\r\n");
      out.write("                                                <p class=\"my-comment\">\r\n");
      out.write("                                                    [내가 입력한건 이렇게 나오게끔]\r\n");
      out.write("                                                </p>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <p class=\"text-right\">\r\n");
      out.write("                                            <input type=\"text\" class=\"searchWord\" placeholder=\" 답글을 입력하세요\">\r\n");
      out.write("                                            <a href=\"#\" class=\"btn btn-outline-primary\"><i class=\"fa fa-reply\"></i> 답글달기</a></p>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <hr>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </article>\r\n");
      out.write("                            \r\n");
      out.write("                            <!--  내 댓글에 대한 답글 article -->\r\n");
      out.write("                        \r\n");
      out.write("                        <article class=\"row\">\r\n");
      out.write("            <div class=\"col-md-9 col-sm-9\">\r\n");
      out.write("              <div class=\"panel panel-default\">\r\n");
      out.write("                <div class=\"panel-body\">\r\n");
      out.write("                  <header class=\"text-right\">\r\n");
      out.write("                    <div class=\"comment-user\"><i class=\"fa fa-user\"></i> [memberId]</div>\r\n");
      out.write("                    <time class=\"comment-date\" datetime=\"16-12-2014 01:05\"><i class=\"fa fa-clock-o\"></i> 2019-10-02 | 15:01</time>\r\n");
      out.write("                  </header>\r\n");
      out.write("                  <div class=\"comment-post\">\r\n");
      out.write("                    <p class=\"my-comment\">\r\n");
      out.write("                      [...........]\r\n");
      out.write("                    </p>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <p class=\"text-right\">\r\n");
      out.write("                  <input type=\"text\" class=\"searchWord\" placeholder=\" 답글을 입력하세요\">\r\n");
      out.write("                  <a href=\"#\" class=\"btn btn-outline-primary\">\r\n");
      out.write("                  <i class=\"fa fa-reply\"></i> 답글달기</a></p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <hr>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-2 col-sm-2 col-md-pull-1 hidden-xs\">\r\n");
      out.write("   \r\n");
      out.write("            </div>\r\n");
      out.write("          </article>\r\n");
      out.write("                            \r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"search-form\">\r\n");
      out.write("                            <input type=\"text\" class=\"searchWord\" placeholder=\" 댓글을 입력하세요\">\r\n");
      out.write("                            <button type=\"button\" style=\"margin-left:10px; font-size:12px;\" class=\"btn btn-outline-primary btn-rounded waves-effect\">입력하기</button>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("    </section>\r\n");
      out.write("</body>\r\n");
      out.write("<footer class=\"ftco-footer ftco-section\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <div class=\"row mb-5\">\r\n");
      out.write("            <div class=\"col-md\">\r\n");
      out.write("                <div class=\"ftco-footer-widget mb-4\">\r\n");
      out.write("                    <h2 class=\"ftco-heading-2\">About <span>SupporterS</span></h2>\r\n");
      out.write("                    <p>창업자가 궁금해하는 것, <br>필요로 하는 것, <br>필요로 할 것들을 최대한 지원하기 위해 만든 사이트입니다.</p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md\">\r\n");
      out.write("                <div class=\"ftco-footer-widget mb-4 ml-md-4\">\r\n");
      out.write("                    <h2 class=\"ftco-heading-2\">바로가기</h2>\r\n");
      out.write("                    <ul class=\"list-unstyled\">\r\n");
      out.write("                        <li><a href=\"/cloud/home\"><span class=\"icon-long-arrow-right mr-2\"></span>Home</a></li>\r\n");
      out.write("                        <li><a href=\"/cloud/member/goPatent\"><span class=\"icon-long-arrow-right mr-2\"></span>검색 및 특허 관련</a></li>\r\n");
      out.write("                        <li><a href=\"/cloud/board/boardListForm\"><span class=\"icon-long-arrow-right mr-2\"></span>Q & A 게시판</a></li>\r\n");
      out.write("                        <li><a href=\"/cloud/survey/surveyListForm\"><span class=\"icon-long-arrow-right mr-2\"></span>블라인드 테스트</a></li>\r\n");
      out.write("                        <li><a href=\"/cloud/funding/fundingListForm\"><span class=\"icon-long-arrow-right mr-2\"></span>크라우드 펀딩</a></li>\r\n");
      out.write("                        <li><a href=\"/cloud/home#contact-section\"><span class=\"icon-long-arrow-right mr-2\"></span>공식 연락처</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md\">\r\n");
      out.write("                <div class=\"ftco-footer-widget mb-4\">\r\n");
      out.write("                    <h2 class=\"ftco-heading-2\">검색 및 특허 관련</h2>\r\n");
      out.write("                    <ul class=\"list-unstyled\">\r\n");
      out.write("                        <li><a href=\"/cloud/member/searchGo\"><span class=\"icon-long-arrow-right mr-2\"> 특허 검색</span></a></li>\r\n");
      out.write("                        <li><a href=\"/cloud/member/\"><span class=\"icon-long-arrow-right mr-2\"> 제품 검색</span></a></li>\r\n");
      out.write("                        <li><a href=\"/cloud/member/goPatent\"><span class=\"icon-long-arrow-right mr-2\"> 특허 출원 신청</span></a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md\">\r\n");
      out.write("                <div class=\"ftco-footer-widget mb-4\">\r\n");
      out.write("                    <h2 class=\"ftco-heading-2\">찾아오는 길</h2>\r\n");
      out.write("                    <div class=\"block-23 mb-0\">\r\n");
      out.write("                        <ul>\r\n");
      out.write("                            <li><span class=\"icon icon-map-marker\"></span><span class=\"text\">4th floor, 513, Yeongdong-daero, Gangnam-gu, Seoul, Republic of Korea</span></li>\r\n");
      out.write("                            <li><a href=\"#\"><span class=\"icon icon-phone\"></span><span class=\"text\">+82 02 6000 0114</span></a></li>\r\n");
      out.write("                            <li><a href=\"#\"><span class=\"icon icon-envelope\"></span><span class=\"text\">info@yourdomain.com</span></a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</footer>\r\n");
      out.write("\r\n");
      out.write("<!-- loader -->\r\n");
      out.write("<div id=\"ftco-loader\" class=\"show fullscreen\"><svg class=\"circular\" width=\"48px\" height=\"48px\">\r\n");
      out.write("        <circle class=\"path-bg\" cx=\"24\" cy=\"24\" r=\"22\" fill=\"none\" stroke-width=\"4\" stroke=\"#eeeeee\" />\r\n");
      out.write("        <circle class=\"path\" cx=\"24\" cy=\"24\" r=\"22\" fill=\"none\" stroke-width=\"4\" stroke-miterlimit=\"10\" stroke=\"#6082cc\" /></svg></div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script src=\"/cloud/resources/js/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"/cloud/resources/js/jquery-migrate-3.0.1.min.js\"></script>\r\n");
      out.write("<script src=\"/cloud/resources/js/popper.min.js\"></script>\r\n");
      out.write("<script src=\"//netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js\"></script>\r\n");
      out.write("<script src=\"/cloud/resources/js/jquery.easing.1.3.js\"></script>\r\n");
      out.write("<script src=\"/cloud/resources/js/jquery.waypoints.min.js\"></script>\r\n");
      out.write("<script src=\"/cloud/resources/js/jquery.stellar.min.js\"></script>\r\n");
      out.write("<script src=\"/cloud/resources/js/owl.carousel.min.js\"></script>\r\n");
      out.write("<script src=\"/cloud/resources/js/jquery.magnific-popup.min.js\"></script>\r\n");
      out.write("<script src=\"/cloud/resources/js/aos.js\"></script>\r\n");
      out.write("<script src=\"/cloud/resources/js/jquery.animateNumber.min.js\"></script>\r\n");
      out.write("<script src=\"/cloud/resources/js/scrollax.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script src=\"/cloud/resources/js/main.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/board/Board_Detail.jsp(52,20) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.loginId==null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                        <li style=\"margin-left: 20px;\" class=\"nav-item cta\">\r\n");
          out.write("                            <div class=\"dropdown show\">\r\n");
          out.write("                                <a class=\"btn btn-primary py-3 px-4\" href=\"#\" role=\"button\" id=\"dropdownMenuLink\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
          out.write("                                    <span class=\"member-btn\">로그인/회원가입</span>\r\n");
          out.write("                                </a>\r\n");
          out.write("\r\n");
          out.write("                                <div class=\"dropdown-menu\" aria-labelledby=\"dropdownMenuLink\">\r\n");
          out.write("                                    <a class=\"dropdown-item\" href=\"/cloud/member/gologin\"><span class=\"member-btn\">로그인</span></a>\r\n");
          out.write("                                    <a class=\"dropdown-item\" href=\"/cloud/member/gosign\"><span class=\"member-btn\">회원가입</span></a>\r\n");
          out.write("                                    <a class=\"dropdown-item\" href=\"/cloud/member/gofindid\"><span class=\"member-btn\">아이디/비밀번호 찾기</span></a>\r\n");
          out.write("                                </div>\r\n");
          out.write("                            </div>\r\n");
          out.write("                        </li>\r\n");
          out.write("                    ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /WEB-INF/views/board/Board_Detail.jsp(68,20) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.loginId!=null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                        <li style=\"margin-left: 20px;\" class=\"nav-item cta\">\r\n");
          out.write("                            <div class=\"dropdown show\">\r\n");
          out.write("                                <a class=\"btn btn-primary py-3 px-4\" href=\"#\" role=\"button\" id=\"dropdownMenuLink\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
          out.write("                                    <span class=\"member-btn\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.loginName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write(' ');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.loginType}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("님</span>\r\n");
          out.write("                                </a>\r\n");
          out.write("\r\n");
          out.write("                                <div class=\"dropdown-menu\" aria-labelledby=\"dropdownMenuLink\">\r\n");
          out.write("                                    <a class=\"dropdown-item\" href=\"/cloud/member/goMypage\">마이페이지</a>\r\n");
          out.write("                                    <a class=\"dropdown-item\" href=\"/cloud/member/goupdate\">회원 정보 수정</a>\r\n");
          out.write("                                    <a class=\"dropdown-item\" href=\"/cloud/member/logout\">로그아웃</a>\r\n");
          out.write("                                </div>\r\n");
          out.write("                            </div>\r\n");
          out.write("                        </li>\r\n");
          out.write("                    ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }
}
